// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v7.34.0
// source: common/error.proto

package common

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_Success             ErrorReason = 0
	ErrorReason_ParamValidate       ErrorReason = 1
	ErrorReason_DataInsert          ErrorReason = 2
	ErrorReason_DataDelete          ErrorReason = 3
	ErrorReason_DataUpdate          ErrorReason = 4
	ErrorReason_DataQuery           ErrorReason = 5
	ErrorReason_DataRecordNotFound  ErrorReason = 6
	ErrorReason_Rpc                 ErrorReason = 7
	ErrorReason_BizDuplicateOp      ErrorReason = 8
	ErrorReason_NotFoundHostNetwork ErrorReason = 9
	ErrorReason_Acl                 ErrorReason = 10
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0:  "Success",
		1:  "ParamValidate",
		2:  "DataInsert",
		3:  "DataDelete",
		4:  "DataUpdate",
		5:  "DataQuery",
		6:  "DataRecordNotFound",
		7:  "Rpc",
		8:  "BizDuplicateOp",
		9:  "NotFoundHostNetwork",
		10: "Acl",
	}
	ErrorReason_value = map[string]int32{
		"Success":             0,
		"ParamValidate":       1,
		"DataInsert":          2,
		"DataDelete":          3,
		"DataUpdate":          4,
		"DataQuery":           5,
		"DataRecordNotFound":  6,
		"Rpc":                 7,
		"BizDuplicateOp":      8,
		"NotFoundHostNetwork": 9,
		"Acl":                 10,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_common_error_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_common_error_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_common_error_proto_rawDescGZIP(), []int{0}
}

var File_common_error_proto protoreflect.FileDescriptor

var file_common_error_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x1a, 0x13, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0xcf, 0x01, 0x0a, 0x0b, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x10, 0x00, 0x12, 0x17, 0x0a, 0x0d, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x56, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x10, 0x01, 0x1a, 0x04, 0xa8, 0x45, 0x90, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x44,
	0x61, 0x74, 0x61, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x44,
	0x61, 0x74, 0x61, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x44,
	0x61, 0x74, 0x61, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09, 0x44,
	0x61, 0x74, 0x61, 0x51, 0x75, 0x65, 0x72, 0x79, 0x10, 0x05, 0x12, 0x16, 0x0a, 0x12, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64,
	0x10, 0x06, 0x12, 0x07, 0x0a, 0x03, 0x52, 0x70, 0x63, 0x10, 0x07, 0x12, 0x12, 0x0a, 0x0e, 0x42,
	0x69, 0x7a, 0x44, 0x75, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x4f, 0x70, 0x10, 0x08, 0x12,
	0x17, 0x0a, 0x13, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x48, 0x6f, 0x73, 0x74, 0x4e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x10, 0x09, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x63, 0x6c, 0x10,
	0x0a, 0x1a, 0x04, 0xa0, 0x45, 0xf4, 0x03, 0x42, 0x1b, 0x5a, 0x19, 0x62, 0x61, 0x63, 0x6b, 0x65,
	0x6e, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x3b, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_error_proto_rawDescOnce sync.Once
	file_common_error_proto_rawDescData = file_common_error_proto_rawDesc
)

func file_common_error_proto_rawDescGZIP() []byte {
	file_common_error_proto_rawDescOnce.Do(func() {
		file_common_error_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_error_proto_rawDescData)
	})
	return file_common_error_proto_rawDescData
}

var file_common_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_error_proto_goTypes = []interface{}{
	(ErrorReason)(0), // 0: api.common.ErrorReason
}
var file_common_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_error_proto_init() }
func file_common_error_proto_init() {
	if File_common_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_error_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_error_proto_goTypes,
		DependencyIndexes: file_common_error_proto_depIdxs,
		EnumInfos:         file_common_error_proto_enumTypes,
	}.Build()
	File_common_error_proto = out.File
	file_common_error_proto_rawDesc = nil
	file_common_error_proto_goTypes = nil
	file_common_error_proto_depIdxs = nil
}
