// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: channel/v1/channel.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Channel_CreateChannel_FullMethodName  = "/channel.v1.Channel/CreateChannel"
	Channel_ListChannels_FullMethodName   = "/channel.v1.Channel/ListChannels"
	Channel_GetChannel_FullMethodName     = "/channel.v1.Channel/GetChannel"
	Channel_UpdateChannel_FullMethodName  = "/channel.v1.Channel/UpdateChannel"
	Channel_DeleteChannel_FullMethodName  = "/channel.v1.Channel/DeleteChannel"
	Channel_SendChannel_FullMethodName    = "/channel.v1.Channel/SendChannel"
	Channel_WebhookInbound_FullMethodName = "/channel.v1.Channel/WebhookInbound"
)

// ChannelClient is the client API for Channel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 渠道管理服务
type ChannelClient interface {
	// 创建渠道
	CreateChannel(ctx context.Context, in *CreateChannelRequest, opts ...grpc.CallOption) (*ChannelReply, error)
	// 渠道列表（分页、筛选）
	ListChannels(ctx context.Context, in *ListChannelsRequest, opts ...grpc.CallOption) (*ListChannelsReply, error)
	// 获取单个渠道
	GetChannel(ctx context.Context, in *GetChannelRequest, opts ...grpc.CallOption) (*ChannelReply, error)
	// 更新渠道
	UpdateChannel(ctx context.Context, in *UpdateChannelRequest, opts ...grpc.CallOption) (*ChannelReply, error)
	// 删除渠道
	DeleteChannel(ctx context.Context, in *DeleteChannelRequest, opts ...grpc.CallOption) (*DeleteChannelReply, error)
	// 向 WxPusher 渠道发送消息
	SendChannel(ctx context.Context, in *SendChannelRequest, opts ...grpc.CallOption) (*SendChannelReply, error)
	// Webhook 入站
	WebhookInbound(ctx context.Context, in *WebhookInboundRequest, opts ...grpc.CallOption) (*WebhookInboundReply, error)
}

type channelClient struct {
	cc grpc.ClientConnInterface
}

func NewChannelClient(cc grpc.ClientConnInterface) ChannelClient {
	return &channelClient{cc}
}

func (c *channelClient) CreateChannel(ctx context.Context, in *CreateChannelRequest, opts ...grpc.CallOption) (*ChannelReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChannelReply)
	err := c.cc.Invoke(ctx, Channel_CreateChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelClient) ListChannels(ctx context.Context, in *ListChannelsRequest, opts ...grpc.CallOption) (*ListChannelsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChannelsReply)
	err := c.cc.Invoke(ctx, Channel_ListChannels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelClient) GetChannel(ctx context.Context, in *GetChannelRequest, opts ...grpc.CallOption) (*ChannelReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChannelReply)
	err := c.cc.Invoke(ctx, Channel_GetChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelClient) UpdateChannel(ctx context.Context, in *UpdateChannelRequest, opts ...grpc.CallOption) (*ChannelReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChannelReply)
	err := c.cc.Invoke(ctx, Channel_UpdateChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelClient) DeleteChannel(ctx context.Context, in *DeleteChannelRequest, opts ...grpc.CallOption) (*DeleteChannelReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteChannelReply)
	err := c.cc.Invoke(ctx, Channel_DeleteChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelClient) SendChannel(ctx context.Context, in *SendChannelRequest, opts ...grpc.CallOption) (*SendChannelReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendChannelReply)
	err := c.cc.Invoke(ctx, Channel_SendChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelClient) WebhookInbound(ctx context.Context, in *WebhookInboundRequest, opts ...grpc.CallOption) (*WebhookInboundReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WebhookInboundReply)
	err := c.cc.Invoke(ctx, Channel_WebhookInbound_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChannelServer is the server API for Channel service.
// All implementations must embed UnimplementedChannelServer
// for forward compatibility.
//
// 渠道管理服务
type ChannelServer interface {
	// 创建渠道
	CreateChannel(context.Context, *CreateChannelRequest) (*ChannelReply, error)
	// 渠道列表（分页、筛选）
	ListChannels(context.Context, *ListChannelsRequest) (*ListChannelsReply, error)
	// 获取单个渠道
	GetChannel(context.Context, *GetChannelRequest) (*ChannelReply, error)
	// 更新渠道
	UpdateChannel(context.Context, *UpdateChannelRequest) (*ChannelReply, error)
	// 删除渠道
	DeleteChannel(context.Context, *DeleteChannelRequest) (*DeleteChannelReply, error)
	// 向 WxPusher 渠道发送消息
	SendChannel(context.Context, *SendChannelRequest) (*SendChannelReply, error)
	// Webhook 入站
	WebhookInbound(context.Context, *WebhookInboundRequest) (*WebhookInboundReply, error)
	mustEmbedUnimplementedChannelServer()
}

// UnimplementedChannelServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChannelServer struct{}

func (UnimplementedChannelServer) CreateChannel(context.Context, *CreateChannelRequest) (*ChannelReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateChannel not implemented")
}
func (UnimplementedChannelServer) ListChannels(context.Context, *ListChannelsRequest) (*ListChannelsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListChannels not implemented")
}
func (UnimplementedChannelServer) GetChannel(context.Context, *GetChannelRequest) (*ChannelReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChannel not implemented")
}
func (UnimplementedChannelServer) UpdateChannel(context.Context, *UpdateChannelRequest) (*ChannelReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateChannel not implemented")
}
func (UnimplementedChannelServer) DeleteChannel(context.Context, *DeleteChannelRequest) (*DeleteChannelReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteChannel not implemented")
}
func (UnimplementedChannelServer) SendChannel(context.Context, *SendChannelRequest) (*SendChannelReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SendChannel not implemented")
}
func (UnimplementedChannelServer) WebhookInbound(context.Context, *WebhookInboundRequest) (*WebhookInboundReply, error) {
	return nil, status.Error(codes.Unimplemented, "method WebhookInbound not implemented")
}
func (UnimplementedChannelServer) mustEmbedUnimplementedChannelServer() {}
func (UnimplementedChannelServer) testEmbeddedByValue()                 {}

// UnsafeChannelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChannelServer will
// result in compilation errors.
type UnsafeChannelServer interface {
	mustEmbedUnimplementedChannelServer()
}

func RegisterChannelServer(s grpc.ServiceRegistrar, srv ChannelServer) {
	// If the following call panics, it indicates UnimplementedChannelServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Channel_ServiceDesc, srv)
}

func _Channel_CreateChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServer).CreateChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Channel_CreateChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServer).CreateChannel(ctx, req.(*CreateChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Channel_ListChannels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChannelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServer).ListChannels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Channel_ListChannels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServer).ListChannels(ctx, req.(*ListChannelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Channel_GetChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServer).GetChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Channel_GetChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServer).GetChannel(ctx, req.(*GetChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Channel_UpdateChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServer).UpdateChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Channel_UpdateChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServer).UpdateChannel(ctx, req.(*UpdateChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Channel_DeleteChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServer).DeleteChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Channel_DeleteChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServer).DeleteChannel(ctx, req.(*DeleteChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Channel_SendChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServer).SendChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Channel_SendChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServer).SendChannel(ctx, req.(*SendChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Channel_WebhookInbound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WebhookInboundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServer).WebhookInbound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Channel_WebhookInbound_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServer).WebhookInbound(ctx, req.(*WebhookInboundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Channel_ServiceDesc is the grpc.ServiceDesc for Channel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Channel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "channel.v1.Channel",
	HandlerType: (*ChannelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateChannel",
			Handler:    _Channel_CreateChannel_Handler,
		},
		{
			MethodName: "ListChannels",
			Handler:    _Channel_ListChannels_Handler,
		},
		{
			MethodName: "GetChannel",
			Handler:    _Channel_GetChannel_Handler,
		},
		{
			MethodName: "UpdateChannel",
			Handler:    _Channel_UpdateChannel_Handler,
		},
		{
			MethodName: "DeleteChannel",
			Handler:    _Channel_DeleteChannel_Handler,
		},
		{
			MethodName: "SendChannel",
			Handler:    _Channel_SendChannel_Handler,
		},
		{
			MethodName: "WebhookInbound",
			Handler:    _Channel_WebhookInbound_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "channel/v1/channel.proto",
}
