// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: channel/v1/channel.proto

package v1

import (
	common "backend/api/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // web | api | webhook | wxpusher | wecom
	DefaultAgent  string                 `protobuf:"bytes,3,opt,name=default_agent,json=defaultAgent,proto3" json:"default_agent,omitempty"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	WebhookPath   string                 `protobuf:"bytes,5,opt,name=webhook_path,json=webhookPath,proto3" json:"webhook_path,omitempty"`
	WebhookSecret string                 `protobuf:"bytes,6,opt,name=webhook_secret,json=webhookSecret,proto3" json:"webhook_secret,omitempty"`
	IpWhitelist   []string               `protobuf:"bytes,7,rep,name=ip_whitelist,json=ipWhitelist,proto3" json:"ip_whitelist,omitempty"`
	AppToken      string                 `protobuf:"bytes,8,opt,name=app_token,json=appToken,proto3" json:"app_token,omitempty"`
	DefaultUids   []string               `protobuf:"bytes,9,rep,name=default_uids,json=defaultUids,proto3" json:"default_uids,omitempty"`
	WebhookUrl    string                 `protobuf:"bytes,10,opt,name=webhook_url,json=webhookUrl,proto3" json:"webhook_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChannelRequest) Reset() {
	*x = CreateChannelRequest{}
	mi := &file_channel_v1_channel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChannelRequest) ProtoMessage() {}

func (x *CreateChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_channel_v1_channel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChannelRequest.ProtoReflect.Descriptor instead.
func (*CreateChannelRequest) Descriptor() ([]byte, []int) {
	return file_channel_v1_channel_proto_rawDescGZIP(), []int{0}
}

func (x *CreateChannelRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *CreateChannelRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateChannelRequest) GetDefaultAgent() string {
	if x != nil {
		return x.DefaultAgent
	}
	return ""
}

func (x *CreateChannelRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *CreateChannelRequest) GetWebhookPath() string {
	if x != nil {
		return x.WebhookPath
	}
	return ""
}

func (x *CreateChannelRequest) GetWebhookSecret() string {
	if x != nil {
		return x.WebhookSecret
	}
	return ""
}

func (x *CreateChannelRequest) GetIpWhitelist() []string {
	if x != nil {
		return x.IpWhitelist
	}
	return nil
}

func (x *CreateChannelRequest) GetAppToken() string {
	if x != nil {
		return x.AppToken
	}
	return ""
}

func (x *CreateChannelRequest) GetDefaultUids() []string {
	if x != nil {
		return x.DefaultUids
	}
	return nil
}

func (x *CreateChannelRequest) GetWebhookUrl() string {
	if x != nil {
		return x.WebhookUrl
	}
	return ""
}

type ListChannelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Enabled       *bool                  `protobuf:"varint,4,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChannelsRequest) Reset() {
	*x = ListChannelsRequest{}
	mi := &file_channel_v1_channel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChannelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChannelsRequest) ProtoMessage() {}

func (x *ListChannelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_channel_v1_channel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChannelsRequest.ProtoReflect.Descriptor instead.
func (*ListChannelsRequest) Descriptor() ([]byte, []int) {
	return file_channel_v1_channel_proto_rawDescGZIP(), []int{1}
}

func (x *ListChannelsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListChannelsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListChannelsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListChannelsRequest) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

type ListChannelsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ret           *common.BaseResponse   `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Items         []*ChannelReply        `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChannelsReply) Reset() {
	*x = ListChannelsReply{}
	mi := &file_channel_v1_channel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChannelsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChannelsReply) ProtoMessage() {}

func (x *ListChannelsReply) ProtoReflect() protoreflect.Message {
	mi := &file_channel_v1_channel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChannelsReply.ProtoReflect.Descriptor instead.
func (*ListChannelsReply) Descriptor() ([]byte, []int) {
	return file_channel_v1_channel_proto_rawDescGZIP(), []int{2}
}

func (x *ListChannelsReply) GetRet() *common.BaseResponse {
	if x != nil {
		return x.Ret
	}
	return nil
}

func (x *ListChannelsReply) GetItems() []*ChannelReply {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListChannelsReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChannelRequest) Reset() {
	*x = GetChannelRequest{}
	mi := &file_channel_v1_channel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChannelRequest) ProtoMessage() {}

func (x *GetChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_channel_v1_channel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChannelRequest.ProtoReflect.Descriptor instead.
func (*GetChannelRequest) Descriptor() ([]byte, []int) {
	return file_channel_v1_channel_proto_rawDescGZIP(), []int{3}
}

func (x *GetChannelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Updates       *structpb.Struct       `protobuf:"bytes,2,opt,name=updates,proto3" json:"updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChannelRequest) Reset() {
	*x = UpdateChannelRequest{}
	mi := &file_channel_v1_channel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChannelRequest) ProtoMessage() {}

func (x *UpdateChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_channel_v1_channel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChannelRequest.ProtoReflect.Descriptor instead.
func (*UpdateChannelRequest) Descriptor() ([]byte, []int) {
	return file_channel_v1_channel_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateChannelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateChannelRequest) GetUpdates() *structpb.Struct {
	if x != nil {
		return x.Updates
	}
	return nil
}

type DeleteChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChannelRequest) Reset() {
	*x = DeleteChannelRequest{}
	mi := &file_channel_v1_channel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChannelRequest) ProtoMessage() {}

func (x *DeleteChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_channel_v1_channel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChannelRequest.ProtoReflect.Descriptor instead.
func (*DeleteChannelRequest) Descriptor() ([]byte, []int) {
	return file_channel_v1_channel_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteChannelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteChannelReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ret           *common.BaseResponse   `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChannelReply) Reset() {
	*x = DeleteChannelReply{}
	mi := &file_channel_v1_channel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChannelReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChannelReply) ProtoMessage() {}

func (x *DeleteChannelReply) ProtoReflect() protoreflect.Message {
	mi := &file_channel_v1_channel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChannelReply.ProtoReflect.Descriptor instead.
func (*DeleteChannelReply) Descriptor() ([]byte, []int) {
	return file_channel_v1_channel_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteChannelReply) GetRet() *common.BaseResponse {
	if x != nil {
		return x.Ret
	}
	return nil
}

type SendChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Uids          []string               `protobuf:"bytes,4,rep,name=uids,proto3" json:"uids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendChannelRequest) Reset() {
	*x = SendChannelRequest{}
	mi := &file_channel_v1_channel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendChannelRequest) ProtoMessage() {}

func (x *SendChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_channel_v1_channel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendChannelRequest.ProtoReflect.Descriptor instead.
func (*SendChannelRequest) Descriptor() ([]byte, []int) {
	return file_channel_v1_channel_proto_rawDescGZIP(), []int{7}
}

func (x *SendChannelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SendChannelRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendChannelRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *SendChannelRequest) GetUids() []string {
	if x != nil {
		return x.Uids
	}
	return nil
}

type SendChannelReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ret           *common.BaseResponse   `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendChannelReply) Reset() {
	*x = SendChannelReply{}
	mi := &file_channel_v1_channel_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendChannelReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendChannelReply) ProtoMessage() {}

func (x *SendChannelReply) ProtoReflect() protoreflect.Message {
	mi := &file_channel_v1_channel_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendChannelReply.ProtoReflect.Descriptor instead.
func (*SendChannelReply) Descriptor() ([]byte, []int) {
	return file_channel_v1_channel_proto_rawDescGZIP(), []int{8}
}

func (x *SendChannelReply) GetRet() *common.BaseResponse {
	if x != nil {
		return x.Ret
	}
	return nil
}

type WebhookInboundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ReplyUrl      string                 `protobuf:"bytes,4,opt,name=reply_url,json=replyUrl,proto3" json:"reply_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookInboundRequest) Reset() {
	*x = WebhookInboundRequest{}
	mi := &file_channel_v1_channel_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookInboundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookInboundRequest) ProtoMessage() {}

func (x *WebhookInboundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_channel_v1_channel_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookInboundRequest.ProtoReflect.Descriptor instead.
func (*WebhookInboundRequest) Descriptor() ([]byte, []int) {
	return file_channel_v1_channel_proto_rawDescGZIP(), []int{9}
}

func (x *WebhookInboundRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *WebhookInboundRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *WebhookInboundRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *WebhookInboundRequest) GetReplyUrl() string {
	if x != nil {
		return x.ReplyUrl
	}
	return ""
}

type WebhookInboundReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ret           *common.BaseResponse   `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Async         bool                   `protobuf:"varint,2,opt,name=async,proto3" json:"async,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookInboundReply) Reset() {
	*x = WebhookInboundReply{}
	mi := &file_channel_v1_channel_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookInboundReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookInboundReply) ProtoMessage() {}

func (x *WebhookInboundReply) ProtoReflect() protoreflect.Message {
	mi := &file_channel_v1_channel_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookInboundReply.ProtoReflect.Descriptor instead.
func (*WebhookInboundReply) Descriptor() ([]byte, []int) {
	return file_channel_v1_channel_proto_rawDescGZIP(), []int{10}
}

func (x *WebhookInboundReply) GetRet() *common.BaseResponse {
	if x != nil {
		return x.Ret
	}
	return nil
}

func (x *WebhookInboundReply) GetAsync() bool {
	if x != nil {
		return x.Async
	}
	return false
}

func (x *WebhookInboundReply) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ChannelReply struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Ret              *common.BaseResponse   `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Id               string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	ChannelId        string                 `protobuf:"bytes,3,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Type             string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	DefaultAgent     string                 `protobuf:"bytes,5,opt,name=default_agent,json=defaultAgent,proto3" json:"default_agent,omitempty"`
	Enabled          bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	WebhookPath      string                 `protobuf:"bytes,7,opt,name=webhook_path,json=webhookPath,proto3" json:"webhook_path,omitempty"`
	IpWhitelist      []string               `protobuf:"bytes,8,rep,name=ip_whitelist,json=ipWhitelist,proto3" json:"ip_whitelist,omitempty"`
	DefaultUids      []string               `protobuf:"bytes,9,rep,name=default_uids,json=defaultUids,proto3" json:"default_uids,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	WebhookUrlMasked string                 `protobuf:"bytes,12,opt,name=webhook_url_masked,json=webhookUrlMasked,proto3" json:"webhook_url_masked,omitempty"` // wecom only; masked display, never full URL
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChannelReply) Reset() {
	*x = ChannelReply{}
	mi := &file_channel_v1_channel_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelReply) ProtoMessage() {}

func (x *ChannelReply) ProtoReflect() protoreflect.Message {
	mi := &file_channel_v1_channel_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelReply.ProtoReflect.Descriptor instead.
func (*ChannelReply) Descriptor() ([]byte, []int) {
	return file_channel_v1_channel_proto_rawDescGZIP(), []int{11}
}

func (x *ChannelReply) GetRet() *common.BaseResponse {
	if x != nil {
		return x.Ret
	}
	return nil
}

func (x *ChannelReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChannelReply) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ChannelReply) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ChannelReply) GetDefaultAgent() string {
	if x != nil {
		return x.DefaultAgent
	}
	return ""
}

func (x *ChannelReply) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ChannelReply) GetWebhookPath() string {
	if x != nil {
		return x.WebhookPath
	}
	return ""
}

func (x *ChannelReply) GetIpWhitelist() []string {
	if x != nil {
		return x.IpWhitelist
	}
	return nil
}

func (x *ChannelReply) GetDefaultUids() []string {
	if x != nil {
		return x.DefaultUids
	}
	return nil
}

func (x *ChannelReply) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ChannelReply) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *ChannelReply) GetWebhookUrlMasked() string {
	if x != nil {
		return x.WebhookUrlMasked
	}
	return ""
}

var File_channel_v1_channel_proto protoreflect.FileDescriptor

const file_channel_v1_channel_proto_rawDesc = "" +
	"\n" +
	"\x18channel/v1/channel.proto\x12\n" +
	"channel.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x13common/common.proto\"\xd6\x02\n" +
	"\x14CreateChannelRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12#\n" +
	"\rdefault_agent\x18\x03 \x01(\tR\fdefaultAgent\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12!\n" +
	"\fwebhook_path\x18\x05 \x01(\tR\vwebhookPath\x12%\n" +
	"\x0ewebhook_secret\x18\x06 \x01(\tR\rwebhookSecret\x12!\n" +
	"\fip_whitelist\x18\a \x03(\tR\vipWhitelist\x12\x1b\n" +
	"\tapp_token\x18\b \x01(\tR\bappToken\x12!\n" +
	"\fdefault_uids\x18\t \x03(\tR\vdefaultUids\x12\x1f\n" +
	"\vwebhook_url\x18\n" +
	" \x01(\tR\n" +
	"webhookUrl\"\x85\x01\n" +
	"\x13ListChannelsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1d\n" +
	"\aenabled\x18\x04 \x01(\bH\x00R\aenabled\x88\x01\x01B\n" +
	"\n" +
	"\b_enabled\"\x85\x01\n" +
	"\x11ListChannelsReply\x12*\n" +
	"\x03ret\x18\x01 \x01(\v2\x18.api.common.BaseResponseR\x03ret\x12.\n" +
	"\x05items\x18\x02 \x03(\v2\x18.channel.v1.ChannelReplyR\x05items\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\"#\n" +
	"\x11GetChannelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Y\n" +
	"\x14UpdateChannelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x121\n" +
	"\aupdates\x18\x02 \x01(\v2\x17.google.protobuf.StructR\aupdates\"&\n" +
	"\x14DeleteChannelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\x12DeleteChannelReply\x12*\n" +
	"\x03ret\x18\x01 \x01(\v2\x18.api.common.BaseResponseR\x03ret\"l\n" +
	"\x12SendChannelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x12\n" +
	"\x04uids\x18\x04 \x03(\tR\x04uids\">\n" +
	"\x10SendChannelReply\x12*\n" +
	"\x03ret\x18\x01 \x01(\v2\x18.api.common.BaseResponseR\x03ret\"\x88\x01\n" +
	"\x15WebhookInboundRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x1b\n" +
	"\treply_url\x18\x04 \x01(\tR\breplyUrl\"q\n" +
	"\x13WebhookInboundReply\x12*\n" +
	"\x03ret\x18\x01 \x01(\v2\x18.api.common.BaseResponseR\x03ret\x12\x14\n" +
	"\x05async\x18\x02 \x01(\bR\x05async\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"\x91\x03\n" +
	"\fChannelReply\x12*\n" +
	"\x03ret\x18\x01 \x01(\v2\x18.api.common.BaseResponseR\x03ret\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x03 \x01(\tR\tchannelId\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12#\n" +
	"\rdefault_agent\x18\x05 \x01(\tR\fdefaultAgent\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x12!\n" +
	"\fwebhook_path\x18\a \x01(\tR\vwebhookPath\x12!\n" +
	"\fip_whitelist\x18\b \x03(\tR\vipWhitelist\x12!\n" +
	"\fdefault_uids\x18\t \x03(\tR\vdefaultUids\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAt\x12,\n" +
	"\x12webhook_url_masked\x18\f \x01(\tR\x10webhookUrlMasked2\x98\x06\n" +
	"\aChannel\x12h\n" +
	"\rCreateChannel\x12 .channel.v1.CreateChannelRequest\x1a\x18.channel.v1.ChannelReply\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/channels\x12h\n" +
	"\fListChannels\x12\x1f.channel.v1.ListChannelsRequest\x1a\x1d.channel.v1.ListChannelsReply\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/v1/channels\x12d\n" +
	"\n" +
	"GetChannel\x12\x1d.channel.v1.GetChannelRequest\x1a\x18.channel.v1.ChannelReply\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/channels/{id}\x12m\n" +
	"\rUpdateChannel\x12 .channel.v1.UpdateChannelRequest\x1a\x18.channel.v1.ChannelReply\" \x82\xd3\xe4\x93\x02\x1a:\x01*\x1a\x15/api/v1/channels/{id}\x12p\n" +
	"\rDeleteChannel\x12 .channel.v1.DeleteChannelRequest\x1a\x1e.channel.v1.DeleteChannelReply\"\x1d\x82\xd3\xe4\x93\x02\x17*\x15/api/v1/channels/{id}\x12r\n" +
	"\vSendChannel\x12\x1e.channel.v1.SendChannelRequest\x1a\x1c.channel.v1.SendChannelReply\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/channels/{id}/send\x12~\n" +
	"\x0eWebhookInbound\x12!.channel.v1.WebhookInboundRequest\x1a\x1f.channel.v1.WebhookInboundReply\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/v1/webhooks/{channel_id}B\x1bZ\x19backend/api/channel/v1;v1b\x06proto3"

var (
	file_channel_v1_channel_proto_rawDescOnce sync.Once
	file_channel_v1_channel_proto_rawDescData []byte
)

func file_channel_v1_channel_proto_rawDescGZIP() []byte {
	file_channel_v1_channel_proto_rawDescOnce.Do(func() {
		file_channel_v1_channel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_channel_v1_channel_proto_rawDesc), len(file_channel_v1_channel_proto_rawDesc)))
	})
	return file_channel_v1_channel_proto_rawDescData
}

var file_channel_v1_channel_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_channel_v1_channel_proto_goTypes = []any{
	(*CreateChannelRequest)(nil),  // 0: channel.v1.CreateChannelRequest
	(*ListChannelsRequest)(nil),   // 1: channel.v1.ListChannelsRequest
	(*ListChannelsReply)(nil),     // 2: channel.v1.ListChannelsReply
	(*GetChannelRequest)(nil),     // 3: channel.v1.GetChannelRequest
	(*UpdateChannelRequest)(nil),  // 4: channel.v1.UpdateChannelRequest
	(*DeleteChannelRequest)(nil),  // 5: channel.v1.DeleteChannelRequest
	(*DeleteChannelReply)(nil),    // 6: channel.v1.DeleteChannelReply
	(*SendChannelRequest)(nil),    // 7: channel.v1.SendChannelRequest
	(*SendChannelReply)(nil),      // 8: channel.v1.SendChannelReply
	(*WebhookInboundRequest)(nil), // 9: channel.v1.WebhookInboundRequest
	(*WebhookInboundReply)(nil),   // 10: channel.v1.WebhookInboundReply
	(*ChannelReply)(nil),          // 11: channel.v1.ChannelReply
	(*common.BaseResponse)(nil),   // 12: api.common.BaseResponse
	(*structpb.Struct)(nil),       // 13: google.protobuf.Struct
}
var file_channel_v1_channel_proto_depIdxs = []int32{
	12, // 0: channel.v1.ListChannelsReply.ret:type_name -> api.common.BaseResponse
	11, // 1: channel.v1.ListChannelsReply.items:type_name -> channel.v1.ChannelReply
	13, // 2: channel.v1.UpdateChannelRequest.updates:type_name -> google.protobuf.Struct
	12, // 3: channel.v1.DeleteChannelReply.ret:type_name -> api.common.BaseResponse
	12, // 4: channel.v1.SendChannelReply.ret:type_name -> api.common.BaseResponse
	12, // 5: channel.v1.WebhookInboundReply.ret:type_name -> api.common.BaseResponse
	12, // 6: channel.v1.ChannelReply.ret:type_name -> api.common.BaseResponse
	0,  // 7: channel.v1.Channel.CreateChannel:input_type -> channel.v1.CreateChannelRequest
	1,  // 8: channel.v1.Channel.ListChannels:input_type -> channel.v1.ListChannelsRequest
	3,  // 9: channel.v1.Channel.GetChannel:input_type -> channel.v1.GetChannelRequest
	4,  // 10: channel.v1.Channel.UpdateChannel:input_type -> channel.v1.UpdateChannelRequest
	5,  // 11: channel.v1.Channel.DeleteChannel:input_type -> channel.v1.DeleteChannelRequest
	7,  // 12: channel.v1.Channel.SendChannel:input_type -> channel.v1.SendChannelRequest
	9,  // 13: channel.v1.Channel.WebhookInbound:input_type -> channel.v1.WebhookInboundRequest
	11, // 14: channel.v1.Channel.CreateChannel:output_type -> channel.v1.ChannelReply
	2,  // 15: channel.v1.Channel.ListChannels:output_type -> channel.v1.ListChannelsReply
	11, // 16: channel.v1.Channel.GetChannel:output_type -> channel.v1.ChannelReply
	11, // 17: channel.v1.Channel.UpdateChannel:output_type -> channel.v1.ChannelReply
	6,  // 18: channel.v1.Channel.DeleteChannel:output_type -> channel.v1.DeleteChannelReply
	8,  // 19: channel.v1.Channel.SendChannel:output_type -> channel.v1.SendChannelReply
	10, // 20: channel.v1.Channel.WebhookInbound:output_type -> channel.v1.WebhookInboundReply
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_channel_v1_channel_proto_init() }
func file_channel_v1_channel_proto_init() {
	if File_channel_v1_channel_proto != nil {
		return
	}
	file_channel_v1_channel_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_channel_v1_channel_proto_rawDesc), len(file_channel_v1_channel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_channel_v1_channel_proto_goTypes,
		DependencyIndexes: file_channel_v1_channel_proto_depIdxs,
		MessageInfos:      file_channel_v1_channel_proto_msgTypes,
	}.Build()
	File_channel_v1_channel_proto = out.File
	file_channel_v1_channel_proto_goTypes = nil
	file_channel_v1_channel_proto_depIdxs = nil
}
