// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.0
// source: channel/v1/channel.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationChannelCreateChannel = "/channel.v1.Channel/CreateChannel"
const OperationChannelDeleteChannel = "/channel.v1.Channel/DeleteChannel"
const OperationChannelGetChannel = "/channel.v1.Channel/GetChannel"
const OperationChannelListChannels = "/channel.v1.Channel/ListChannels"
const OperationChannelSendChannel = "/channel.v1.Channel/SendChannel"
const OperationChannelUpdateChannel = "/channel.v1.Channel/UpdateChannel"
const OperationChannelWebhookInbound = "/channel.v1.Channel/WebhookInbound"

type ChannelHTTPServer interface {
	// CreateChannel 创建渠道
	CreateChannel(context.Context, *CreateChannelRequest) (*ChannelReply, error)
	// DeleteChannel 删除渠道
	DeleteChannel(context.Context, *DeleteChannelRequest) (*DeleteChannelReply, error)
	// GetChannel 获取单个渠道
	GetChannel(context.Context, *GetChannelRequest) (*ChannelReply, error)
	// ListChannels 渠道列表（分页、筛选）
	ListChannels(context.Context, *ListChannelsRequest) (*ListChannelsReply, error)
	// SendChannel 向 WxPusher 渠道发送消息
	SendChannel(context.Context, *SendChannelRequest) (*SendChannelReply, error)
	// UpdateChannel 更新渠道
	UpdateChannel(context.Context, *UpdateChannelRequest) (*ChannelReply, error)
	// WebhookInbound Webhook 入站
	WebhookInbound(context.Context, *WebhookInboundRequest) (*WebhookInboundReply, error)
}

func RegisterChannelHTTPServer(s *http.Server, srv ChannelHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/channels", _Channel_CreateChannel0_HTTP_Handler(srv))
	r.GET("/api/v1/channels", _Channel_ListChannels0_HTTP_Handler(srv))
	r.GET("/api/v1/channels/{id}", _Channel_GetChannel0_HTTP_Handler(srv))
	r.PUT("/api/v1/channels/{id}", _Channel_UpdateChannel0_HTTP_Handler(srv))
	r.DELETE("/api/v1/channels/{id}", _Channel_DeleteChannel0_HTTP_Handler(srv))
	r.POST("/api/v1/channels/{id}/send", _Channel_SendChannel0_HTTP_Handler(srv))
	r.POST("/api/v1/webhooks/{channel_id}", _Channel_WebhookInbound0_HTTP_Handler(srv))
}

func _Channel_CreateChannel0_HTTP_Handler(srv ChannelHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateChannelRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChannelCreateChannel)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateChannel(ctx, req.(*CreateChannelRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ChannelReply)
		return ctx.Result(200, reply)
	}
}

func _Channel_ListChannels0_HTTP_Handler(srv ChannelHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListChannelsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChannelListChannels)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListChannels(ctx, req.(*ListChannelsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListChannelsReply)
		return ctx.Result(200, reply)
	}
}

func _Channel_GetChannel0_HTTP_Handler(srv ChannelHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetChannelRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChannelGetChannel)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetChannel(ctx, req.(*GetChannelRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ChannelReply)
		return ctx.Result(200, reply)
	}
}

func _Channel_UpdateChannel0_HTTP_Handler(srv ChannelHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateChannelRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChannelUpdateChannel)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateChannel(ctx, req.(*UpdateChannelRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ChannelReply)
		return ctx.Result(200, reply)
	}
}

func _Channel_DeleteChannel0_HTTP_Handler(srv ChannelHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteChannelRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChannelDeleteChannel)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteChannel(ctx, req.(*DeleteChannelRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteChannelReply)
		return ctx.Result(200, reply)
	}
}

func _Channel_SendChannel0_HTTP_Handler(srv ChannelHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SendChannelRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChannelSendChannel)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SendChannel(ctx, req.(*SendChannelRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SendChannelReply)
		return ctx.Result(200, reply)
	}
}

func _Channel_WebhookInbound0_HTTP_Handler(srv ChannelHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in WebhookInboundRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChannelWebhookInbound)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.WebhookInbound(ctx, req.(*WebhookInboundRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*WebhookInboundReply)
		return ctx.Result(200, reply)
	}
}

type ChannelHTTPClient interface {
	// CreateChannel 创建渠道
	CreateChannel(ctx context.Context, req *CreateChannelRequest, opts ...http.CallOption) (rsp *ChannelReply, err error)
	// DeleteChannel 删除渠道
	DeleteChannel(ctx context.Context, req *DeleteChannelRequest, opts ...http.CallOption) (rsp *DeleteChannelReply, err error)
	// GetChannel 获取单个渠道
	GetChannel(ctx context.Context, req *GetChannelRequest, opts ...http.CallOption) (rsp *ChannelReply, err error)
	// ListChannels 渠道列表（分页、筛选）
	ListChannels(ctx context.Context, req *ListChannelsRequest, opts ...http.CallOption) (rsp *ListChannelsReply, err error)
	// SendChannel 向 WxPusher 渠道发送消息
	SendChannel(ctx context.Context, req *SendChannelRequest, opts ...http.CallOption) (rsp *SendChannelReply, err error)
	// UpdateChannel 更新渠道
	UpdateChannel(ctx context.Context, req *UpdateChannelRequest, opts ...http.CallOption) (rsp *ChannelReply, err error)
	// WebhookInbound Webhook 入站
	WebhookInbound(ctx context.Context, req *WebhookInboundRequest, opts ...http.CallOption) (rsp *WebhookInboundReply, err error)
}

type ChannelHTTPClientImpl struct {
	cc *http.Client
}

func NewChannelHTTPClient(client *http.Client) ChannelHTTPClient {
	return &ChannelHTTPClientImpl{client}
}

// CreateChannel 创建渠道
func (c *ChannelHTTPClientImpl) CreateChannel(ctx context.Context, in *CreateChannelRequest, opts ...http.CallOption) (*ChannelReply, error) {
	var out ChannelReply
	pattern := "/api/v1/channels"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationChannelCreateChannel))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteChannel 删除渠道
func (c *ChannelHTTPClientImpl) DeleteChannel(ctx context.Context, in *DeleteChannelRequest, opts ...http.CallOption) (*DeleteChannelReply, error) {
	var out DeleteChannelReply
	pattern := "/api/v1/channels/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationChannelDeleteChannel))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetChannel 获取单个渠道
func (c *ChannelHTTPClientImpl) GetChannel(ctx context.Context, in *GetChannelRequest, opts ...http.CallOption) (*ChannelReply, error) {
	var out ChannelReply
	pattern := "/api/v1/channels/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationChannelGetChannel))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListChannels 渠道列表（分页、筛选）
func (c *ChannelHTTPClientImpl) ListChannels(ctx context.Context, in *ListChannelsRequest, opts ...http.CallOption) (*ListChannelsReply, error) {
	var out ListChannelsReply
	pattern := "/api/v1/channels"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationChannelListChannels))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SendChannel 向 WxPusher 渠道发送消息
func (c *ChannelHTTPClientImpl) SendChannel(ctx context.Context, in *SendChannelRequest, opts ...http.CallOption) (*SendChannelReply, error) {
	var out SendChannelReply
	pattern := "/api/v1/channels/{id}/send"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationChannelSendChannel))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateChannel 更新渠道
func (c *ChannelHTTPClientImpl) UpdateChannel(ctx context.Context, in *UpdateChannelRequest, opts ...http.CallOption) (*ChannelReply, error) {
	var out ChannelReply
	pattern := "/api/v1/channels/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationChannelUpdateChannel))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// WebhookInbound Webhook 入站
func (c *ChannelHTTPClientImpl) WebhookInbound(ctx context.Context, in *WebhookInboundRequest, opts ...http.CallOption) (*WebhookInboundReply, error) {
	var out WebhookInboundReply
	pattern := "/api/v1/webhooks/{channel_id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationChannelWebhookInbound))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
