// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.0
// source: chat/v1/chat.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationChatCreateSession = "/chat.v1.Chat/CreateSession"
const OperationChatDeleteSession = "/chat.v1.Chat/DeleteSession"
const OperationChatGetSession = "/chat.v1.Chat/GetSession"
const OperationChatListAllSessions = "/chat.v1.Chat/ListAllSessions"
const OperationChatListMessages = "/chat.v1.Chat/ListMessages"
const OperationChatListSessions = "/chat.v1.Chat/ListSessions"
const OperationChatSearchSessions = "/chat.v1.Chat/SearchSessions"
const OperationChatSendMessage = "/chat.v1.Chat/SendMessage"
const OperationChatUpdateSession = "/chat.v1.Chat/UpdateSession"

type ChatHTTPServer interface {
	// CreateSession 新建会话
	CreateSession(context.Context, *CreateSessionRequest) (*SessionReply, error)
	// DeleteSession 删除会话（级联删除消息）
	DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionReply, error)
	// GetSession 获取会话详情
	GetSession(context.Context, *GetSessionRequest) (*SessionReply, error)
	// ListAllSessions 跨 Agent 分页列出会话（全局历史）
	ListAllSessions(context.Context, *ListAllSessionsRequest) (*ListAllSessionsReply, error)
	// ListMessages 获取会话内消息历史（按时间升序）
	ListMessages(context.Context, *ListMessagesRequest) (*ListMessagesReply, error)
	// ListSessions 获取该 Agent 的会话列表（分页）
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsReply, error)
	// SearchSessions 跨 Agent FTS 搜索会话
	SearchSessions(context.Context, *SearchSessionsRequest) (*SearchSessionsReply, error)
	// SendMessage 发送用户消息，触发 Agent 回复（支持流式 SSE，Accept: text/event-stream）
	SendMessage(context.Context, *SendMessageRequest) (*MessageReply, error)
	// UpdateSession 更新会话（如标题）
	UpdateSession(context.Context, *UpdateSessionRequest) (*SessionReply, error)
}

func RegisterChatHTTPServer(s *http.Server, srv ChatHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/agents/{agent_id}/sessions", _Chat_CreateSession0_HTTP_Handler(srv))
	r.GET("/api/v1/agents/{agent_id}/sessions", _Chat_ListSessions0_HTTP_Handler(srv))
	r.GET("/api/v1/sessions", _Chat_ListAllSessions0_HTTP_Handler(srv))
	r.GET("/api/v1/sessions/search", _Chat_SearchSessions0_HTTP_Handler(srv))
	r.GET("/api/v1/sessions/{id}", _Chat_GetSession0_HTTP_Handler(srv))
	r.PUT("/api/v1/sessions/{id}", _Chat_UpdateSession0_HTTP_Handler(srv))
	r.DELETE("/api/v1/sessions/{id}", _Chat_DeleteSession0_HTTP_Handler(srv))
	r.POST("/api/v1/sessions/{session_id}/messages", _Chat_SendMessage0_HTTP_Handler(srv))
	r.GET("/api/v1/sessions/{session_id}/messages", _Chat_ListMessages0_HTTP_Handler(srv))
}

func _Chat_CreateSession0_HTTP_Handler(srv ChatHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateSessionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChatCreateSession)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateSession(ctx, req.(*CreateSessionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SessionReply)
		return ctx.Result(200, reply)
	}
}

func _Chat_ListSessions0_HTTP_Handler(srv ChatHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSessionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChatListSessions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSessions(ctx, req.(*ListSessionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSessionsReply)
		return ctx.Result(200, reply)
	}
}

func _Chat_ListAllSessions0_HTTP_Handler(srv ChatHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAllSessionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChatListAllSessions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAllSessions(ctx, req.(*ListAllSessionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAllSessionsReply)
		return ctx.Result(200, reply)
	}
}

func _Chat_SearchSessions0_HTTP_Handler(srv ChatHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SearchSessionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChatSearchSessions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SearchSessions(ctx, req.(*SearchSessionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SearchSessionsReply)
		return ctx.Result(200, reply)
	}
}

func _Chat_GetSession0_HTTP_Handler(srv ChatHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSessionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChatGetSession)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSession(ctx, req.(*GetSessionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SessionReply)
		return ctx.Result(200, reply)
	}
}

func _Chat_UpdateSession0_HTTP_Handler(srv ChatHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateSessionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChatUpdateSession)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateSession(ctx, req.(*UpdateSessionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SessionReply)
		return ctx.Result(200, reply)
	}
}

func _Chat_DeleteSession0_HTTP_Handler(srv ChatHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteSessionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChatDeleteSession)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteSession(ctx, req.(*DeleteSessionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteSessionReply)
		return ctx.Result(200, reply)
	}
}

func _Chat_SendMessage0_HTTP_Handler(srv ChatHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SendMessageRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChatSendMessage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SendMessage(ctx, req.(*SendMessageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MessageReply)
		return ctx.Result(200, reply)
	}
}

func _Chat_ListMessages0_HTTP_Handler(srv ChatHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListMessagesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChatListMessages)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMessages(ctx, req.(*ListMessagesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListMessagesReply)
		return ctx.Result(200, reply)
	}
}

type ChatHTTPClient interface {
	// CreateSession 新建会话
	CreateSession(ctx context.Context, req *CreateSessionRequest, opts ...http.CallOption) (rsp *SessionReply, err error)
	// DeleteSession 删除会话（级联删除消息）
	DeleteSession(ctx context.Context, req *DeleteSessionRequest, opts ...http.CallOption) (rsp *DeleteSessionReply, err error)
	// GetSession 获取会话详情
	GetSession(ctx context.Context, req *GetSessionRequest, opts ...http.CallOption) (rsp *SessionReply, err error)
	// ListAllSessions 跨 Agent 分页列出会话（全局历史）
	ListAllSessions(ctx context.Context, req *ListAllSessionsRequest, opts ...http.CallOption) (rsp *ListAllSessionsReply, err error)
	// ListMessages 获取会话内消息历史（按时间升序）
	ListMessages(ctx context.Context, req *ListMessagesRequest, opts ...http.CallOption) (rsp *ListMessagesReply, err error)
	// ListSessions 获取该 Agent 的会话列表（分页）
	ListSessions(ctx context.Context, req *ListSessionsRequest, opts ...http.CallOption) (rsp *ListSessionsReply, err error)
	// SearchSessions 跨 Agent FTS 搜索会话
	SearchSessions(ctx context.Context, req *SearchSessionsRequest, opts ...http.CallOption) (rsp *SearchSessionsReply, err error)
	// SendMessage 发送用户消息，触发 Agent 回复（支持流式 SSE，Accept: text/event-stream）
	SendMessage(ctx context.Context, req *SendMessageRequest, opts ...http.CallOption) (rsp *MessageReply, err error)
	// UpdateSession 更新会话（如标题）
	UpdateSession(ctx context.Context, req *UpdateSessionRequest, opts ...http.CallOption) (rsp *SessionReply, err error)
}

type ChatHTTPClientImpl struct {
	cc *http.Client
}

func NewChatHTTPClient(client *http.Client) ChatHTTPClient {
	return &ChatHTTPClientImpl{client}
}

// CreateSession 新建会话
func (c *ChatHTTPClientImpl) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...http.CallOption) (*SessionReply, error) {
	var out SessionReply
	pattern := "/api/v1/agents/{agent_id}/sessions"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationChatCreateSession))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteSession 删除会话（级联删除消息）
func (c *ChatHTTPClientImpl) DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...http.CallOption) (*DeleteSessionReply, error) {
	var out DeleteSessionReply
	pattern := "/api/v1/sessions/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationChatDeleteSession))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetSession 获取会话详情
func (c *ChatHTTPClientImpl) GetSession(ctx context.Context, in *GetSessionRequest, opts ...http.CallOption) (*SessionReply, error) {
	var out SessionReply
	pattern := "/api/v1/sessions/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationChatGetSession))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAllSessions 跨 Agent 分页列出会话（全局历史）
func (c *ChatHTTPClientImpl) ListAllSessions(ctx context.Context, in *ListAllSessionsRequest, opts ...http.CallOption) (*ListAllSessionsReply, error) {
	var out ListAllSessionsReply
	pattern := "/api/v1/sessions"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationChatListAllSessions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListMessages 获取会话内消息历史（按时间升序）
func (c *ChatHTTPClientImpl) ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...http.CallOption) (*ListMessagesReply, error) {
	var out ListMessagesReply
	pattern := "/api/v1/sessions/{session_id}/messages"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationChatListMessages))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListSessions 获取该 Agent 的会话列表（分页）
func (c *ChatHTTPClientImpl) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...http.CallOption) (*ListSessionsReply, error) {
	var out ListSessionsReply
	pattern := "/api/v1/agents/{agent_id}/sessions"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationChatListSessions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SearchSessions 跨 Agent FTS 搜索会话
func (c *ChatHTTPClientImpl) SearchSessions(ctx context.Context, in *SearchSessionsRequest, opts ...http.CallOption) (*SearchSessionsReply, error) {
	var out SearchSessionsReply
	pattern := "/api/v1/sessions/search"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationChatSearchSessions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SendMessage 发送用户消息，触发 Agent 回复（支持流式 SSE，Accept: text/event-stream）
func (c *ChatHTTPClientImpl) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...http.CallOption) (*MessageReply, error) {
	var out MessageReply
	pattern := "/api/v1/sessions/{session_id}/messages"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationChatSendMessage))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateSession 更新会话（如标题）
func (c *ChatHTTPClientImpl) UpdateSession(ctx context.Context, in *UpdateSessionRequest, opts ...http.CallOption) (*SessionReply, error) {
	var out SessionReply
	pattern := "/api/v1/sessions/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationChatUpdateSession))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
