// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: cron/v1/cron.proto

package v1

import (
	common "backend/api/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCronTaskRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AgentId            string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ScheduleKind       string                 `protobuf:"bytes,3,opt,name=schedule_kind,json=scheduleKind,proto3" json:"schedule_kind,omitempty"` // cron | every | at
	ScheduleExpr       string                 `protobuf:"bytes,4,opt,name=schedule_expr,json=scheduleExpr,proto3" json:"schedule_expr,omitempty"`
	Timezone           string                 `protobuf:"bytes,5,opt,name=timezone,proto3" json:"timezone,omitempty"`
	StaggerSec         int32                  `protobuf:"varint,6,opt,name=stagger_sec,json=staggerSec,proto3" json:"stagger_sec,omitempty"`
	PayloadKind        string                 `protobuf:"bytes,7,opt,name=payload_kind,json=payloadKind,proto3" json:"payload_kind,omitempty"` // agent_turn | skill_execute
	PayloadContent     string                 `protobuf:"bytes,8,opt,name=payload_content,json=payloadContent,proto3" json:"payload_content,omitempty"`
	TimeoutSec         int32                  `protobuf:"varint,9,opt,name=timeout_sec,json=timeoutSec,proto3" json:"timeout_sec,omitempty"`
	RetryCount         int32                  `protobuf:"varint,10,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	RetryIntervalSec   int32                  `protobuf:"varint,11,opt,name=retry_interval_sec,json=retryIntervalSec,proto3" json:"retry_interval_sec,omitempty"`
	DeliveryMode       string                 `protobuf:"bytes,12,opt,name=delivery_mode,json=deliveryMode,proto3" json:"delivery_mode,omitempty"` // none | webhook | session | channel
	DeliveryWebhookUrl string                 `protobuf:"bytes,13,opt,name=delivery_webhook_url,json=deliveryWebhookUrl,proto3" json:"delivery_webhook_url,omitempty"`
	DeliverySecret     string                 `protobuf:"bytes,14,opt,name=delivery_secret,json=deliverySecret,proto3" json:"delivery_secret,omitempty"`
	DeliveryBestEffort bool                   `protobuf:"varint,15,opt,name=delivery_best_effort,json=deliveryBestEffort,proto3" json:"delivery_best_effort,omitempty"`
	DeliverySessionId  string                 `protobuf:"bytes,16,opt,name=delivery_session_id,json=deliverySessionId,proto3" json:"delivery_session_id,omitempty"`
	DeliveryChannelId  string                 `protobuf:"bytes,17,opt,name=delivery_channel_id,json=deliveryChannelId,proto3" json:"delivery_channel_id,omitempty"`
	Enabled            bool                   `protobuf:"varint,18,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateCronTaskRequest) Reset() {
	*x = CreateCronTaskRequest{}
	mi := &file_cron_v1_cron_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCronTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCronTaskRequest) ProtoMessage() {}

func (x *CreateCronTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cron_v1_cron_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCronTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateCronTaskRequest) Descriptor() ([]byte, []int) {
	return file_cron_v1_cron_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCronTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCronTaskRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CreateCronTaskRequest) GetScheduleKind() string {
	if x != nil {
		return x.ScheduleKind
	}
	return ""
}

func (x *CreateCronTaskRequest) GetScheduleExpr() string {
	if x != nil {
		return x.ScheduleExpr
	}
	return ""
}

func (x *CreateCronTaskRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *CreateCronTaskRequest) GetStaggerSec() int32 {
	if x != nil {
		return x.StaggerSec
	}
	return 0
}

func (x *CreateCronTaskRequest) GetPayloadKind() string {
	if x != nil {
		return x.PayloadKind
	}
	return ""
}

func (x *CreateCronTaskRequest) GetPayloadContent() string {
	if x != nil {
		return x.PayloadContent
	}
	return ""
}

func (x *CreateCronTaskRequest) GetTimeoutSec() int32 {
	if x != nil {
		return x.TimeoutSec
	}
	return 0
}

func (x *CreateCronTaskRequest) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *CreateCronTaskRequest) GetRetryIntervalSec() int32 {
	if x != nil {
		return x.RetryIntervalSec
	}
	return 0
}

func (x *CreateCronTaskRequest) GetDeliveryMode() string {
	if x != nil {
		return x.DeliveryMode
	}
	return ""
}

func (x *CreateCronTaskRequest) GetDeliveryWebhookUrl() string {
	if x != nil {
		return x.DeliveryWebhookUrl
	}
	return ""
}

func (x *CreateCronTaskRequest) GetDeliverySecret() string {
	if x != nil {
		return x.DeliverySecret
	}
	return ""
}

func (x *CreateCronTaskRequest) GetDeliveryBestEffort() bool {
	if x != nil {
		return x.DeliveryBestEffort
	}
	return false
}

func (x *CreateCronTaskRequest) GetDeliverySessionId() string {
	if x != nil {
		return x.DeliverySessionId
	}
	return ""
}

func (x *CreateCronTaskRequest) GetDeliveryChannelId() string {
	if x != nil {
		return x.DeliveryChannelId
	}
	return ""
}

func (x *CreateCronTaskRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type ListCronTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Enabled       *bool                  `protobuf:"varint,4,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCronTasksRequest) Reset() {
	*x = ListCronTasksRequest{}
	mi := &file_cron_v1_cron_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCronTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCronTasksRequest) ProtoMessage() {}

func (x *ListCronTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cron_v1_cron_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCronTasksRequest.ProtoReflect.Descriptor instead.
func (*ListCronTasksRequest) Descriptor() ([]byte, []int) {
	return file_cron_v1_cron_proto_rawDescGZIP(), []int{1}
}

func (x *ListCronTasksRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCronTasksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCronTasksRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ListCronTasksRequest) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

type ListCronTasksReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ret           *common.BaseResponse   `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Items         []*CronTaskReply       `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCronTasksReply) Reset() {
	*x = ListCronTasksReply{}
	mi := &file_cron_v1_cron_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCronTasksReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCronTasksReply) ProtoMessage() {}

func (x *ListCronTasksReply) ProtoReflect() protoreflect.Message {
	mi := &file_cron_v1_cron_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCronTasksReply.ProtoReflect.Descriptor instead.
func (*ListCronTasksReply) Descriptor() ([]byte, []int) {
	return file_cron_v1_cron_proto_rawDescGZIP(), []int{2}
}

func (x *ListCronTasksReply) GetRet() *common.BaseResponse {
	if x != nil {
		return x.Ret
	}
	return nil
}

func (x *ListCronTasksReply) GetItems() []*CronTaskReply {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListCronTasksReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetCronTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCronTaskRequest) Reset() {
	*x = GetCronTaskRequest{}
	mi := &file_cron_v1_cron_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCronTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCronTaskRequest) ProtoMessage() {}

func (x *GetCronTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cron_v1_cron_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCronTaskRequest.ProtoReflect.Descriptor instead.
func (*GetCronTaskRequest) Descriptor() ([]byte, []int) {
	return file_cron_v1_cron_proto_rawDescGZIP(), []int{3}
}

func (x *GetCronTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateCronTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Updates       *structpb.Struct       `protobuf:"bytes,2,opt,name=updates,proto3" json:"updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCronTaskRequest) Reset() {
	*x = UpdateCronTaskRequest{}
	mi := &file_cron_v1_cron_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCronTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCronTaskRequest) ProtoMessage() {}

func (x *UpdateCronTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cron_v1_cron_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCronTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateCronTaskRequest) Descriptor() ([]byte, []int) {
	return file_cron_v1_cron_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateCronTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCronTaskRequest) GetUpdates() *structpb.Struct {
	if x != nil {
		return x.Updates
	}
	return nil
}

type DeleteCronTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCronTaskRequest) Reset() {
	*x = DeleteCronTaskRequest{}
	mi := &file_cron_v1_cron_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCronTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCronTaskRequest) ProtoMessage() {}

func (x *DeleteCronTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cron_v1_cron_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCronTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteCronTaskRequest) Descriptor() ([]byte, []int) {
	return file_cron_v1_cron_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCronTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCronTaskReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ret           *common.BaseResponse   `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCronTaskReply) Reset() {
	*x = DeleteCronTaskReply{}
	mi := &file_cron_v1_cron_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCronTaskReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCronTaskReply) ProtoMessage() {}

func (x *DeleteCronTaskReply) ProtoReflect() protoreflect.Message {
	mi := &file_cron_v1_cron_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCronTaskReply.ProtoReflect.Descriptor instead.
func (*DeleteCronTaskReply) Descriptor() ([]byte, []int) {
	return file_cron_v1_cron_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteCronTaskReply) GetRet() *common.BaseResponse {
	if x != nil {
		return x.Ret
	}
	return nil
}

type RunCronTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCronTaskRequest) Reset() {
	*x = RunCronTaskRequest{}
	mi := &file_cron_v1_cron_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCronTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCronTaskRequest) ProtoMessage() {}

func (x *RunCronTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cron_v1_cron_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCronTaskRequest.ProtoReflect.Descriptor instead.
func (*RunCronTaskRequest) Descriptor() ([]byte, []int) {
	return file_cron_v1_cron_proto_rawDescGZIP(), []int{7}
}

func (x *RunCronTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RunCronTaskReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ret           *common.BaseResponse   `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCronTaskReply) Reset() {
	*x = RunCronTaskReply{}
	mi := &file_cron_v1_cron_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCronTaskReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCronTaskReply) ProtoMessage() {}

func (x *RunCronTaskReply) ProtoReflect() protoreflect.Message {
	mi := &file_cron_v1_cron_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCronTaskReply.ProtoReflect.Descriptor instead.
func (*RunCronTaskReply) Descriptor() ([]byte, []int) {
	return file_cron_v1_cron_proto_rawDescGZIP(), []int{8}
}

func (x *RunCronTaskReply) GetRet() *common.BaseResponse {
	if x != nil {
		return x.Ret
	}
	return nil
}

type ListCronRunsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCronRunsRequest) Reset() {
	*x = ListCronRunsRequest{}
	mi := &file_cron_v1_cron_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCronRunsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCronRunsRequest) ProtoMessage() {}

func (x *ListCronRunsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cron_v1_cron_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCronRunsRequest.ProtoReflect.Descriptor instead.
func (*ListCronRunsRequest) Descriptor() ([]byte, []int) {
	return file_cron_v1_cron_proto_rawDescGZIP(), []int{9}
}

func (x *ListCronRunsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListCronRunsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCronRunsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListCronRunsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ret           *common.BaseResponse   `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Items         []*CronRunReply        `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCronRunsReply) Reset() {
	*x = ListCronRunsReply{}
	mi := &file_cron_v1_cron_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCronRunsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCronRunsReply) ProtoMessage() {}

func (x *ListCronRunsReply) ProtoReflect() protoreflect.Message {
	mi := &file_cron_v1_cron_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCronRunsReply.ProtoReflect.Descriptor instead.
func (*ListCronRunsReply) Descriptor() ([]byte, []int) {
	return file_cron_v1_cron_proto_rawDescGZIP(), []int{10}
}

func (x *ListCronRunsReply) GetRet() *common.BaseResponse {
	if x != nil {
		return x.Ret
	}
	return nil
}

func (x *ListCronRunsReply) GetItems() []*CronRunReply {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListCronRunsReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CronTaskReply struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Ret                *common.BaseResponse   `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Id                 string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	AgentId            string                 `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ScheduleKind       string                 `protobuf:"bytes,5,opt,name=schedule_kind,json=scheduleKind,proto3" json:"schedule_kind,omitempty"`
	ScheduleExpr       string                 `protobuf:"bytes,6,opt,name=schedule_expr,json=scheduleExpr,proto3" json:"schedule_expr,omitempty"`
	Timezone           string                 `protobuf:"bytes,7,opt,name=timezone,proto3" json:"timezone,omitempty"`
	StaggerSec         int32                  `protobuf:"varint,8,opt,name=stagger_sec,json=staggerSec,proto3" json:"stagger_sec,omitempty"`
	PayloadKind        string                 `protobuf:"bytes,9,opt,name=payload_kind,json=payloadKind,proto3" json:"payload_kind,omitempty"`
	PayloadContent     string                 `protobuf:"bytes,10,opt,name=payload_content,json=payloadContent,proto3" json:"payload_content,omitempty"`
	TimeoutSec         int32                  `protobuf:"varint,11,opt,name=timeout_sec,json=timeoutSec,proto3" json:"timeout_sec,omitempty"`
	RetryCount         int32                  `protobuf:"varint,12,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	RetryIntervalSec   int32                  `protobuf:"varint,13,opt,name=retry_interval_sec,json=retryIntervalSec,proto3" json:"retry_interval_sec,omitempty"`
	DeliveryMode       string                 `protobuf:"bytes,14,opt,name=delivery_mode,json=deliveryMode,proto3" json:"delivery_mode,omitempty"`
	DeliveryWebhookUrl string                 `protobuf:"bytes,15,opt,name=delivery_webhook_url,json=deliveryWebhookUrl,proto3" json:"delivery_webhook_url,omitempty"`
	DeliverySessionId  string                 `protobuf:"bytes,16,opt,name=delivery_session_id,json=deliverySessionId,proto3" json:"delivery_session_id,omitempty"`
	DeliveryChannelId  string                 `protobuf:"bytes,17,opt,name=delivery_channel_id,json=deliveryChannelId,proto3" json:"delivery_channel_id,omitempty"`
	Enabled            bool                   `protobuf:"varint,18,opt,name=enabled,proto3" json:"enabled,omitempty"`
	NextRunAt          string                 `protobuf:"bytes,19,opt,name=next_run_at,json=nextRunAt,proto3" json:"next_run_at,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          string                 `protobuf:"bytes,21,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CronTaskReply) Reset() {
	*x = CronTaskReply{}
	mi := &file_cron_v1_cron_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CronTaskReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronTaskReply) ProtoMessage() {}

func (x *CronTaskReply) ProtoReflect() protoreflect.Message {
	mi := &file_cron_v1_cron_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronTaskReply.ProtoReflect.Descriptor instead.
func (*CronTaskReply) Descriptor() ([]byte, []int) {
	return file_cron_v1_cron_proto_rawDescGZIP(), []int{11}
}

func (x *CronTaskReply) GetRet() *common.BaseResponse {
	if x != nil {
		return x.Ret
	}
	return nil
}

func (x *CronTaskReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CronTaskReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CronTaskReply) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CronTaskReply) GetScheduleKind() string {
	if x != nil {
		return x.ScheduleKind
	}
	return ""
}

func (x *CronTaskReply) GetScheduleExpr() string {
	if x != nil {
		return x.ScheduleExpr
	}
	return ""
}

func (x *CronTaskReply) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *CronTaskReply) GetStaggerSec() int32 {
	if x != nil {
		return x.StaggerSec
	}
	return 0
}

func (x *CronTaskReply) GetPayloadKind() string {
	if x != nil {
		return x.PayloadKind
	}
	return ""
}

func (x *CronTaskReply) GetPayloadContent() string {
	if x != nil {
		return x.PayloadContent
	}
	return ""
}

func (x *CronTaskReply) GetTimeoutSec() int32 {
	if x != nil {
		return x.TimeoutSec
	}
	return 0
}

func (x *CronTaskReply) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *CronTaskReply) GetRetryIntervalSec() int32 {
	if x != nil {
		return x.RetryIntervalSec
	}
	return 0
}

func (x *CronTaskReply) GetDeliveryMode() string {
	if x != nil {
		return x.DeliveryMode
	}
	return ""
}

func (x *CronTaskReply) GetDeliveryWebhookUrl() string {
	if x != nil {
		return x.DeliveryWebhookUrl
	}
	return ""
}

func (x *CronTaskReply) GetDeliverySessionId() string {
	if x != nil {
		return x.DeliverySessionId
	}
	return ""
}

func (x *CronTaskReply) GetDeliveryChannelId() string {
	if x != nil {
		return x.DeliveryChannelId
	}
	return ""
}

func (x *CronTaskReply) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *CronTaskReply) GetNextRunAt() string {
	if x != nil {
		return x.NextRunAt
	}
	return ""
}

func (x *CronTaskReply) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CronTaskReply) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CronRunReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TriggeredAt   string                 `protobuf:"bytes,3,opt,name=triggered_at,json=triggeredAt,proto3" json:"triggered_at,omitempty"`
	StartedAt     string                 `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    string                 `protobuf:"bytes,5,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	OutputSummary string                 `protobuf:"bytes,7,opt,name=output_summary,json=outputSummary,proto3" json:"output_summary,omitempty"`
	Error         string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	DeliveryOk    *bool                  `protobuf:"varint,9,opt,name=delivery_ok,json=deliveryOk,proto3,oneof" json:"delivery_ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CronRunReply) Reset() {
	*x = CronRunReply{}
	mi := &file_cron_v1_cron_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CronRunReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronRunReply) ProtoMessage() {}

func (x *CronRunReply) ProtoReflect() protoreflect.Message {
	mi := &file_cron_v1_cron_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronRunReply.ProtoReflect.Descriptor instead.
func (*CronRunReply) Descriptor() ([]byte, []int) {
	return file_cron_v1_cron_proto_rawDescGZIP(), []int{12}
}

func (x *CronRunReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CronRunReply) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CronRunReply) GetTriggeredAt() string {
	if x != nil {
		return x.TriggeredAt
	}
	return ""
}

func (x *CronRunReply) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *CronRunReply) GetFinishedAt() string {
	if x != nil {
		return x.FinishedAt
	}
	return ""
}

func (x *CronRunReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CronRunReply) GetOutputSummary() string {
	if x != nil {
		return x.OutputSummary
	}
	return ""
}

func (x *CronRunReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CronRunReply) GetDeliveryOk() bool {
	if x != nil && x.DeliveryOk != nil {
		return *x.DeliveryOk
	}
	return false
}

var File_cron_v1_cron_proto protoreflect.FileDescriptor

const file_cron_v1_cron_proto_rawDesc = "" +
	"\n" +
	"\x12cron/v1/cron.proto\x12\acron.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x13common/common.proto\"\xb5\x05\n" +
	"\x15CreateCronTaskRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12#\n" +
	"\rschedule_kind\x18\x03 \x01(\tR\fscheduleKind\x12#\n" +
	"\rschedule_expr\x18\x04 \x01(\tR\fscheduleExpr\x12\x1a\n" +
	"\btimezone\x18\x05 \x01(\tR\btimezone\x12\x1f\n" +
	"\vstagger_sec\x18\x06 \x01(\x05R\n" +
	"staggerSec\x12!\n" +
	"\fpayload_kind\x18\a \x01(\tR\vpayloadKind\x12'\n" +
	"\x0fpayload_content\x18\b \x01(\tR\x0epayloadContent\x12\x1f\n" +
	"\vtimeout_sec\x18\t \x01(\x05R\n" +
	"timeoutSec\x12\x1f\n" +
	"\vretry_count\x18\n" +
	" \x01(\x05R\n" +
	"retryCount\x12,\n" +
	"\x12retry_interval_sec\x18\v \x01(\x05R\x10retryIntervalSec\x12#\n" +
	"\rdelivery_mode\x18\f \x01(\tR\fdeliveryMode\x120\n" +
	"\x14delivery_webhook_url\x18\r \x01(\tR\x12deliveryWebhookUrl\x12'\n" +
	"\x0fdelivery_secret\x18\x0e \x01(\tR\x0edeliverySecret\x120\n" +
	"\x14delivery_best_effort\x18\x0f \x01(\bR\x12deliveryBestEffort\x12.\n" +
	"\x13delivery_session_id\x18\x10 \x01(\tR\x11deliverySessionId\x12.\n" +
	"\x13delivery_channel_id\x18\x11 \x01(\tR\x11deliveryChannelId\x12\x18\n" +
	"\aenabled\x18\x12 \x01(\bR\aenabled\"\x8d\x01\n" +
	"\x14ListCronTasksRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x1d\n" +
	"\aenabled\x18\x04 \x01(\bH\x00R\aenabled\x88\x01\x01B\n" +
	"\n" +
	"\b_enabled\"\x84\x01\n" +
	"\x12ListCronTasksReply\x12*\n" +
	"\x03ret\x18\x01 \x01(\v2\x18.api.common.BaseResponseR\x03ret\x12,\n" +
	"\x05items\x18\x02 \x03(\v2\x16.cron.v1.CronTaskReplyR\x05items\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\"$\n" +
	"\x12GetCronTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Z\n" +
	"\x15UpdateCronTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x121\n" +
	"\aupdates\x18\x02 \x01(\v2\x17.google.protobuf.StructR\aupdates\"'\n" +
	"\x15DeleteCronTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"A\n" +
	"\x13DeleteCronTaskReply\x12*\n" +
	"\x03ret\x18\x01 \x01(\v2\x18.api.common.BaseResponseR\x03ret\"$\n" +
	"\x12RunCronTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\">\n" +
	"\x10RunCronTaskReply\x12*\n" +
	"\x03ret\x18\x01 \x01(\v2\x18.api.common.BaseResponseR\x03ret\"V\n" +
	"\x13ListCronRunsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\x82\x01\n" +
	"\x11ListCronRunsReply\x12*\n" +
	"\x03ret\x18\x01 \x01(\v2\x18.api.common.BaseResponseR\x03ret\x12+\n" +
	"\x05items\x18\x02 \x03(\v2\x15.cron.v1.CronRunReplyR\x05items\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\"\xec\x05\n" +
	"\rCronTaskReply\x12*\n" +
	"\x03ret\x18\x01 \x01(\v2\x18.api.common.BaseResponseR\x03ret\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\tR\aagentId\x12#\n" +
	"\rschedule_kind\x18\x05 \x01(\tR\fscheduleKind\x12#\n" +
	"\rschedule_expr\x18\x06 \x01(\tR\fscheduleExpr\x12\x1a\n" +
	"\btimezone\x18\a \x01(\tR\btimezone\x12\x1f\n" +
	"\vstagger_sec\x18\b \x01(\x05R\n" +
	"staggerSec\x12!\n" +
	"\fpayload_kind\x18\t \x01(\tR\vpayloadKind\x12'\n" +
	"\x0fpayload_content\x18\n" +
	" \x01(\tR\x0epayloadContent\x12\x1f\n" +
	"\vtimeout_sec\x18\v \x01(\x05R\n" +
	"timeoutSec\x12\x1f\n" +
	"\vretry_count\x18\f \x01(\x05R\n" +
	"retryCount\x12,\n" +
	"\x12retry_interval_sec\x18\r \x01(\x05R\x10retryIntervalSec\x12#\n" +
	"\rdelivery_mode\x18\x0e \x01(\tR\fdeliveryMode\x120\n" +
	"\x14delivery_webhook_url\x18\x0f \x01(\tR\x12deliveryWebhookUrl\x12.\n" +
	"\x13delivery_session_id\x18\x10 \x01(\tR\x11deliverySessionId\x12.\n" +
	"\x13delivery_channel_id\x18\x11 \x01(\tR\x11deliveryChannelId\x12\x18\n" +
	"\aenabled\x18\x12 \x01(\bR\aenabled\x12\x1e\n" +
	"\vnext_run_at\x18\x13 \x01(\tR\tnextRunAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x14 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x15 \x01(\tR\tupdatedAt\"\xa5\x02\n" +
	"\fCronRunReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12!\n" +
	"\ftriggered_at\x18\x03 \x01(\tR\vtriggeredAt\x12\x1d\n" +
	"\n" +
	"started_at\x18\x04 \x01(\tR\tstartedAt\x12\x1f\n" +
	"\vfinished_at\x18\x05 \x01(\tR\n" +
	"finishedAt\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12%\n" +
	"\x0eoutput_summary\x18\a \x01(\tR\routputSummary\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x12$\n" +
	"\vdelivery_ok\x18\t \x01(\bH\x00R\n" +
	"deliveryOk\x88\x01\x01B\x0e\n" +
	"\f_delivery_ok2\xf8\x05\n" +
	"\x04Cron\x12g\n" +
	"\x0eCreateCronTask\x12\x1e.cron.v1.CreateCronTaskRequest\x1a\x16.cron.v1.CronTaskReply\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/cron/tasks\x12g\n" +
	"\rListCronTasks\x12\x1d.cron.v1.ListCronTasksRequest\x1a\x1b.cron.v1.ListCronTasksReply\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/cron/tasks\x12c\n" +
	"\vGetCronTask\x12\x1b.cron.v1.GetCronTaskRequest\x1a\x16.cron.v1.CronTaskReply\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/cron/tasks/{id}\x12l\n" +
	"\x0eUpdateCronTask\x12\x1e.cron.v1.UpdateCronTaskRequest\x1a\x16.cron.v1.CronTaskReply\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\x1a\x17/api/v1/cron/tasks/{id}\x12o\n" +
	"\x0eDeleteCronTask\x12\x1e.cron.v1.DeleteCronTaskRequest\x1a\x1c.cron.v1.DeleteCronTaskReply\"\x1f\x82\xd3\xe4\x93\x02\x19*\x17/api/v1/cron/tasks/{id}\x12j\n" +
	"\vRunCronTask\x12\x1b.cron.v1.RunCronTaskRequest\x1a\x19.cron.v1.RunCronTaskReply\"#\x82\xd3\xe4\x93\x02\x1d\"\x1b/api/v1/cron/tasks/{id}/run\x12n\n" +
	"\fListCronRuns\x12\x1c.cron.v1.ListCronRunsRequest\x1a\x1a.cron.v1.ListCronRunsReply\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/v1/cron/tasks/{id}/runsB\x18Z\x16backend/api/cron/v1;v1b\x06proto3"

var (
	file_cron_v1_cron_proto_rawDescOnce sync.Once
	file_cron_v1_cron_proto_rawDescData []byte
)

func file_cron_v1_cron_proto_rawDescGZIP() []byte {
	file_cron_v1_cron_proto_rawDescOnce.Do(func() {
		file_cron_v1_cron_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cron_v1_cron_proto_rawDesc), len(file_cron_v1_cron_proto_rawDesc)))
	})
	return file_cron_v1_cron_proto_rawDescData
}

var file_cron_v1_cron_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_cron_v1_cron_proto_goTypes = []any{
	(*CreateCronTaskRequest)(nil), // 0: cron.v1.CreateCronTaskRequest
	(*ListCronTasksRequest)(nil),  // 1: cron.v1.ListCronTasksRequest
	(*ListCronTasksReply)(nil),    // 2: cron.v1.ListCronTasksReply
	(*GetCronTaskRequest)(nil),    // 3: cron.v1.GetCronTaskRequest
	(*UpdateCronTaskRequest)(nil), // 4: cron.v1.UpdateCronTaskRequest
	(*DeleteCronTaskRequest)(nil), // 5: cron.v1.DeleteCronTaskRequest
	(*DeleteCronTaskReply)(nil),   // 6: cron.v1.DeleteCronTaskReply
	(*RunCronTaskRequest)(nil),    // 7: cron.v1.RunCronTaskRequest
	(*RunCronTaskReply)(nil),      // 8: cron.v1.RunCronTaskReply
	(*ListCronRunsRequest)(nil),   // 9: cron.v1.ListCronRunsRequest
	(*ListCronRunsReply)(nil),     // 10: cron.v1.ListCronRunsReply
	(*CronTaskReply)(nil),         // 11: cron.v1.CronTaskReply
	(*CronRunReply)(nil),          // 12: cron.v1.CronRunReply
	(*common.BaseResponse)(nil),   // 13: api.common.BaseResponse
	(*structpb.Struct)(nil),       // 14: google.protobuf.Struct
}
var file_cron_v1_cron_proto_depIdxs = []int32{
	13, // 0: cron.v1.ListCronTasksReply.ret:type_name -> api.common.BaseResponse
	11, // 1: cron.v1.ListCronTasksReply.items:type_name -> cron.v1.CronTaskReply
	14, // 2: cron.v1.UpdateCronTaskRequest.updates:type_name -> google.protobuf.Struct
	13, // 3: cron.v1.DeleteCronTaskReply.ret:type_name -> api.common.BaseResponse
	13, // 4: cron.v1.RunCronTaskReply.ret:type_name -> api.common.BaseResponse
	13, // 5: cron.v1.ListCronRunsReply.ret:type_name -> api.common.BaseResponse
	12, // 6: cron.v1.ListCronRunsReply.items:type_name -> cron.v1.CronRunReply
	13, // 7: cron.v1.CronTaskReply.ret:type_name -> api.common.BaseResponse
	0,  // 8: cron.v1.Cron.CreateCronTask:input_type -> cron.v1.CreateCronTaskRequest
	1,  // 9: cron.v1.Cron.ListCronTasks:input_type -> cron.v1.ListCronTasksRequest
	3,  // 10: cron.v1.Cron.GetCronTask:input_type -> cron.v1.GetCronTaskRequest
	4,  // 11: cron.v1.Cron.UpdateCronTask:input_type -> cron.v1.UpdateCronTaskRequest
	5,  // 12: cron.v1.Cron.DeleteCronTask:input_type -> cron.v1.DeleteCronTaskRequest
	7,  // 13: cron.v1.Cron.RunCronTask:input_type -> cron.v1.RunCronTaskRequest
	9,  // 14: cron.v1.Cron.ListCronRuns:input_type -> cron.v1.ListCronRunsRequest
	11, // 15: cron.v1.Cron.CreateCronTask:output_type -> cron.v1.CronTaskReply
	2,  // 16: cron.v1.Cron.ListCronTasks:output_type -> cron.v1.ListCronTasksReply
	11, // 17: cron.v1.Cron.GetCronTask:output_type -> cron.v1.CronTaskReply
	11, // 18: cron.v1.Cron.UpdateCronTask:output_type -> cron.v1.CronTaskReply
	6,  // 19: cron.v1.Cron.DeleteCronTask:output_type -> cron.v1.DeleteCronTaskReply
	8,  // 20: cron.v1.Cron.RunCronTask:output_type -> cron.v1.RunCronTaskReply
	10, // 21: cron.v1.Cron.ListCronRuns:output_type -> cron.v1.ListCronRunsReply
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_cron_v1_cron_proto_init() }
func file_cron_v1_cron_proto_init() {
	if File_cron_v1_cron_proto != nil {
		return
	}
	file_cron_v1_cron_proto_msgTypes[1].OneofWrappers = []any{}
	file_cron_v1_cron_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cron_v1_cron_proto_rawDesc), len(file_cron_v1_cron_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cron_v1_cron_proto_goTypes,
		DependencyIndexes: file_cron_v1_cron_proto_depIdxs,
		MessageInfos:      file_cron_v1_cron_proto_msgTypes,
	}.Build()
	File_cron_v1_cron_proto = out.File
	file_cron_v1_cron_proto_goTypes = nil
	file_cron_v1_cron_proto_depIdxs = nil
}
