// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.34.0
// source: cron/v1/cron.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Cron_CreateCronTask_FullMethodName = "/cron.v1.Cron/CreateCronTask"
	Cron_ListCronTasks_FullMethodName  = "/cron.v1.Cron/ListCronTasks"
	Cron_GetCronTask_FullMethodName    = "/cron.v1.Cron/GetCronTask"
	Cron_UpdateCronTask_FullMethodName = "/cron.v1.Cron/UpdateCronTask"
	Cron_DeleteCronTask_FullMethodName = "/cron.v1.Cron/DeleteCronTask"
	Cron_RunCronTask_FullMethodName    = "/cron.v1.Cron/RunCronTask"
	Cron_ListCronRuns_FullMethodName   = "/cron.v1.Cron/ListCronRuns"
)

// CronClient is the client API for Cron service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CronClient interface {
	// 创建定时任务
	CreateCronTask(ctx context.Context, in *CreateCronTaskRequest, opts ...grpc.CallOption) (*CronTaskReply, error)
	// 任务列表（分页、筛选）
	ListCronTasks(ctx context.Context, in *ListCronTasksRequest, opts ...grpc.CallOption) (*ListCronTasksReply, error)
	// 获取单个任务
	GetCronTask(ctx context.Context, in *GetCronTaskRequest, opts ...grpc.CallOption) (*CronTaskReply, error)
	// 更新任务
	UpdateCronTask(ctx context.Context, in *UpdateCronTaskRequest, opts ...grpc.CallOption) (*CronTaskReply, error)
	// 删除任务
	DeleteCronTask(ctx context.Context, in *DeleteCronTaskRequest, opts ...grpc.CallOption) (*DeleteCronTaskReply, error)
	// 立即执行
	RunCronTask(ctx context.Context, in *RunCronTaskRequest, opts ...grpc.CallOption) (*RunCronTaskReply, error)
	// 执行历史
	ListCronRuns(ctx context.Context, in *ListCronRunsRequest, opts ...grpc.CallOption) (*ListCronRunsReply, error)
}

type cronClient struct {
	cc grpc.ClientConnInterface
}

func NewCronClient(cc grpc.ClientConnInterface) CronClient {
	return &cronClient{cc}
}

func (c *cronClient) CreateCronTask(ctx context.Context, in *CreateCronTaskRequest, opts ...grpc.CallOption) (*CronTaskReply, error) {
	out := new(CronTaskReply)
	err := c.cc.Invoke(ctx, Cron_CreateCronTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronClient) ListCronTasks(ctx context.Context, in *ListCronTasksRequest, opts ...grpc.CallOption) (*ListCronTasksReply, error) {
	out := new(ListCronTasksReply)
	err := c.cc.Invoke(ctx, Cron_ListCronTasks_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronClient) GetCronTask(ctx context.Context, in *GetCronTaskRequest, opts ...grpc.CallOption) (*CronTaskReply, error) {
	out := new(CronTaskReply)
	err := c.cc.Invoke(ctx, Cron_GetCronTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronClient) UpdateCronTask(ctx context.Context, in *UpdateCronTaskRequest, opts ...grpc.CallOption) (*CronTaskReply, error) {
	out := new(CronTaskReply)
	err := c.cc.Invoke(ctx, Cron_UpdateCronTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronClient) DeleteCronTask(ctx context.Context, in *DeleteCronTaskRequest, opts ...grpc.CallOption) (*DeleteCronTaskReply, error) {
	out := new(DeleteCronTaskReply)
	err := c.cc.Invoke(ctx, Cron_DeleteCronTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronClient) RunCronTask(ctx context.Context, in *RunCronTaskRequest, opts ...grpc.CallOption) (*RunCronTaskReply, error) {
	out := new(RunCronTaskReply)
	err := c.cc.Invoke(ctx, Cron_RunCronTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronClient) ListCronRuns(ctx context.Context, in *ListCronRunsRequest, opts ...grpc.CallOption) (*ListCronRunsReply, error) {
	out := new(ListCronRunsReply)
	err := c.cc.Invoke(ctx, Cron_ListCronRuns_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CronServer is the server API for Cron service.
// All implementations must embed UnimplementedCronServer
// for forward compatibility
type CronServer interface {
	// 创建定时任务
	CreateCronTask(context.Context, *CreateCronTaskRequest) (*CronTaskReply, error)
	// 任务列表（分页、筛选）
	ListCronTasks(context.Context, *ListCronTasksRequest) (*ListCronTasksReply, error)
	// 获取单个任务
	GetCronTask(context.Context, *GetCronTaskRequest) (*CronTaskReply, error)
	// 更新任务
	UpdateCronTask(context.Context, *UpdateCronTaskRequest) (*CronTaskReply, error)
	// 删除任务
	DeleteCronTask(context.Context, *DeleteCronTaskRequest) (*DeleteCronTaskReply, error)
	// 立即执行
	RunCronTask(context.Context, *RunCronTaskRequest) (*RunCronTaskReply, error)
	// 执行历史
	ListCronRuns(context.Context, *ListCronRunsRequest) (*ListCronRunsReply, error)
	mustEmbedUnimplementedCronServer()
}

// UnimplementedCronServer must be embedded to have forward compatible implementations.
type UnimplementedCronServer struct {
}

func (UnimplementedCronServer) CreateCronTask(context.Context, *CreateCronTaskRequest) (*CronTaskReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCronTask not implemented")
}
func (UnimplementedCronServer) ListCronTasks(context.Context, *ListCronTasksRequest) (*ListCronTasksReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCronTasks not implemented")
}
func (UnimplementedCronServer) GetCronTask(context.Context, *GetCronTaskRequest) (*CronTaskReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCronTask not implemented")
}
func (UnimplementedCronServer) UpdateCronTask(context.Context, *UpdateCronTaskRequest) (*CronTaskReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCronTask not implemented")
}
func (UnimplementedCronServer) DeleteCronTask(context.Context, *DeleteCronTaskRequest) (*DeleteCronTaskReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCronTask not implemented")
}
func (UnimplementedCronServer) RunCronTask(context.Context, *RunCronTaskRequest) (*RunCronTaskReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunCronTask not implemented")
}
func (UnimplementedCronServer) ListCronRuns(context.Context, *ListCronRunsRequest) (*ListCronRunsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCronRuns not implemented")
}
func (UnimplementedCronServer) mustEmbedUnimplementedCronServer() {}

// UnsafeCronServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CronServer will
// result in compilation errors.
type UnsafeCronServer interface {
	mustEmbedUnimplementedCronServer()
}

func RegisterCronServer(s grpc.ServiceRegistrar, srv CronServer) {
	s.RegisterService(&Cron_ServiceDesc, srv)
}

func _Cron_CreateCronTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCronTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServer).CreateCronTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cron_CreateCronTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServer).CreateCronTask(ctx, req.(*CreateCronTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cron_ListCronTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCronTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServer).ListCronTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cron_ListCronTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServer).ListCronTasks(ctx, req.(*ListCronTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cron_GetCronTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCronTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServer).GetCronTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cron_GetCronTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServer).GetCronTask(ctx, req.(*GetCronTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cron_UpdateCronTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCronTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServer).UpdateCronTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cron_UpdateCronTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServer).UpdateCronTask(ctx, req.(*UpdateCronTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cron_DeleteCronTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCronTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServer).DeleteCronTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cron_DeleteCronTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServer).DeleteCronTask(ctx, req.(*DeleteCronTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cron_RunCronTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunCronTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServer).RunCronTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cron_RunCronTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServer).RunCronTask(ctx, req.(*RunCronTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cron_ListCronRuns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCronRunsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServer).ListCronRuns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cron_ListCronRuns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServer).ListCronRuns(ctx, req.(*ListCronRunsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Cron_ServiceDesc is the grpc.ServiceDesc for Cron service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Cron_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cron.v1.Cron",
	HandlerType: (*CronServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCronTask",
			Handler:    _Cron_CreateCronTask_Handler,
		},
		{
			MethodName: "ListCronTasks",
			Handler:    _Cron_ListCronTasks_Handler,
		},
		{
			MethodName: "GetCronTask",
			Handler:    _Cron_GetCronTask_Handler,
		},
		{
			MethodName: "UpdateCronTask",
			Handler:    _Cron_UpdateCronTask_Handler,
		},
		{
			MethodName: "DeleteCronTask",
			Handler:    _Cron_DeleteCronTask_Handler,
		},
		{
			MethodName: "RunCronTask",
			Handler:    _Cron_RunCronTask_Handler,
		},
		{
			MethodName: "ListCronRuns",
			Handler:    _Cron_ListCronRuns_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cron/v1/cron.proto",
}
