// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.0
// source: agent/v1/agent.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAgentBindTools = "/agent.v1.Agent/BindTools"
const OperationAgentChat = "/agent.v1.Agent/Chat"
const OperationAgentCreateAgent = "/agent.v1.Agent/CreateAgent"
const OperationAgentDeleteAgent = "/agent.v1.Agent/DeleteAgent"
const OperationAgentDeleteSkill = "/agent.v1.Agent/DeleteSkill"
const OperationAgentExecuteSkill = "/agent.v1.Agent/ExecuteSkill"
const OperationAgentGetAgent = "/agent.v1.Agent/GetAgent"
const OperationAgentListAgents = "/agent.v1.Agent/ListAgents"
const OperationAgentListSkills = "/agent.v1.Agent/ListSkills"
const OperationAgentUnbindTools = "/agent.v1.Agent/UnbindTools"
const OperationAgentUpdateAgent = "/agent.v1.Agent/UpdateAgent"
const OperationAgentUploadSkillPackage = "/agent.v1.Agent/UploadSkillPackage"
const OperationAgentValidateSkillPackage = "/agent.v1.Agent/ValidateSkillPackage"

type AgentHTTPServer interface {
	// BindTools 绑定工具
	BindTools(context.Context, *BindToolsRequest) (*BindToolsReply, error)
	// Chat 与 Agent 对话
	Chat(context.Context, *ChatRequest) (*ChatReply, error)
	// CreateAgent 创建 Agent
	CreateAgent(context.Context, *CreateAgentRequest) (*AgentReply, error)
	// DeleteAgent 删除 Agent
	DeleteAgent(context.Context, *DeleteAgentRequest) (*DeleteAgentReply, error)
	// DeleteSkill 删除指定技能，移除 workspace/skills/{skill_name}/ 目录及其下所有文件
	DeleteSkill(context.Context, *DeleteSkillRequest) (*DeleteSkillReply, error)
	// ExecuteSkill 执行技能脚本（调试用）
	ExecuteSkill(context.Context, *ExecuteSkillRequest) (*ExecuteSkillReply, error)
	// GetAgent 获取单个 Agent
	GetAgent(context.Context, *GetAgentRequest) (*AgentReply, error)
	// ListAgents Agent 列表（分页）
	ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsReply, error)
	// ListSkills 列出该 Agent 下所有技能（扫描 workspace/skills 子目录，含 SKILL.md 视为有效）
	ListSkills(context.Context, *ListSkillsRequest) (*ListSkillsReply, error)
	// UnbindTools 解绑工具
	UnbindTools(context.Context, *UnbindToolsRequest) (*UnbindToolsReply, error)
	// UpdateAgent 更新 Agent
	UpdateAgent(context.Context, *UpdateAgentRequest) (*AgentReply, error)
	// UploadSkillPackage 上传技能包（校验通过后解压到 workspace/skills）
	UploadSkillPackage(context.Context, *UploadSkillPackageRequest) (*UploadSkillPackageReply, error)
	// ValidateSkillPackage 校验技能包（仅校验不解压）
	ValidateSkillPackage(context.Context, *ValidateSkillPackageRequest) (*ValidateSkillPackageReply, error)
}

func RegisterAgentHTTPServer(s *http.Server, srv AgentHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/agents", _Agent_CreateAgent0_HTTP_Handler(srv))
	r.GET("/api/v1/agents/{id}", _Agent_GetAgent0_HTTP_Handler(srv))
	r.GET("/api/v1/agents", _Agent_ListAgents0_HTTP_Handler(srv))
	r.PUT("/api/v1/agents/{id}", _Agent_UpdateAgent0_HTTP_Handler(srv))
	r.DELETE("/api/v1/agents/{id}", _Agent_DeleteAgent0_HTTP_Handler(srv))
	r.POST("/api/v1/agents/{id}/tools", _Agent_BindTools0_HTTP_Handler(srv))
	r.DELETE("/api/v1/agents/{id}/tools", _Agent_UnbindTools0_HTTP_Handler(srv))
	r.POST("/api/v1/agents/{id}/chat", _Agent_Chat0_HTTP_Handler(srv))
	r.POST("/api/v1/agents/{id}/skills/validate", _Agent_ValidateSkillPackage0_HTTP_Handler(srv))
	r.POST("/api/v1/agents/{id}/skills/upload", _Agent_UploadSkillPackage0_HTTP_Handler(srv))
	r.POST("/api/v1/agents/{id}/skills/execute", _Agent_ExecuteSkill0_HTTP_Handler(srv))
	r.GET("/api/v1/agents/{id}/skills", _Agent_ListSkills0_HTTP_Handler(srv))
	r.DELETE("/api/v1/agents/{id}/skills/{skill_name}", _Agent_DeleteSkill0_HTTP_Handler(srv))
}

func _Agent_CreateAgent0_HTTP_Handler(srv AgentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateAgentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentCreateAgent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateAgent(ctx, req.(*CreateAgentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AgentReply)
		return ctx.Result(200, reply)
	}
}

func _Agent_GetAgent0_HTTP_Handler(srv AgentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAgentRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentGetAgent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAgent(ctx, req.(*GetAgentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AgentReply)
		return ctx.Result(200, reply)
	}
}

func _Agent_ListAgents0_HTTP_Handler(srv AgentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAgentsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentListAgents)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAgents(ctx, req.(*ListAgentsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAgentsReply)
		return ctx.Result(200, reply)
	}
}

func _Agent_UpdateAgent0_HTTP_Handler(srv AgentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateAgentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentUpdateAgent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateAgent(ctx, req.(*UpdateAgentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AgentReply)
		return ctx.Result(200, reply)
	}
}

func _Agent_DeleteAgent0_HTTP_Handler(srv AgentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteAgentRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentDeleteAgent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteAgent(ctx, req.(*DeleteAgentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteAgentReply)
		return ctx.Result(200, reply)
	}
}

func _Agent_BindTools0_HTTP_Handler(srv AgentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BindToolsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentBindTools)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BindTools(ctx, req.(*BindToolsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BindToolsReply)
		return ctx.Result(200, reply)
	}
}

func _Agent_UnbindTools0_HTTP_Handler(srv AgentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UnbindToolsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentUnbindTools)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UnbindTools(ctx, req.(*UnbindToolsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UnbindToolsReply)
		return ctx.Result(200, reply)
	}
}

func _Agent_Chat0_HTTP_Handler(srv AgentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ChatRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentChat)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Chat(ctx, req.(*ChatRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ChatReply)
		return ctx.Result(200, reply)
	}
}

func _Agent_ValidateSkillPackage0_HTTP_Handler(srv AgentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ValidateSkillPackageRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentValidateSkillPackage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ValidateSkillPackage(ctx, req.(*ValidateSkillPackageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ValidateSkillPackageReply)
		return ctx.Result(200, reply)
	}
}

func _Agent_UploadSkillPackage0_HTTP_Handler(srv AgentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UploadSkillPackageRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentUploadSkillPackage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UploadSkillPackage(ctx, req.(*UploadSkillPackageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UploadSkillPackageReply)
		return ctx.Result(200, reply)
	}
}

func _Agent_ExecuteSkill0_HTTP_Handler(srv AgentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ExecuteSkillRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentExecuteSkill)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ExecuteSkill(ctx, req.(*ExecuteSkillRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ExecuteSkillReply)
		return ctx.Result(200, reply)
	}
}

func _Agent_ListSkills0_HTTP_Handler(srv AgentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSkillsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentListSkills)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSkills(ctx, req.(*ListSkillsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSkillsReply)
		return ctx.Result(200, reply)
	}
}

func _Agent_DeleteSkill0_HTTP_Handler(srv AgentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteSkillRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentDeleteSkill)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteSkill(ctx, req.(*DeleteSkillRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteSkillReply)
		return ctx.Result(200, reply)
	}
}

type AgentHTTPClient interface {
	// BindTools 绑定工具
	BindTools(ctx context.Context, req *BindToolsRequest, opts ...http.CallOption) (rsp *BindToolsReply, err error)
	// Chat 与 Agent 对话
	Chat(ctx context.Context, req *ChatRequest, opts ...http.CallOption) (rsp *ChatReply, err error)
	// CreateAgent 创建 Agent
	CreateAgent(ctx context.Context, req *CreateAgentRequest, opts ...http.CallOption) (rsp *AgentReply, err error)
	// DeleteAgent 删除 Agent
	DeleteAgent(ctx context.Context, req *DeleteAgentRequest, opts ...http.CallOption) (rsp *DeleteAgentReply, err error)
	// DeleteSkill 删除指定技能，移除 workspace/skills/{skill_name}/ 目录及其下所有文件
	DeleteSkill(ctx context.Context, req *DeleteSkillRequest, opts ...http.CallOption) (rsp *DeleteSkillReply, err error)
	// ExecuteSkill 执行技能脚本（调试用）
	ExecuteSkill(ctx context.Context, req *ExecuteSkillRequest, opts ...http.CallOption) (rsp *ExecuteSkillReply, err error)
	// GetAgent 获取单个 Agent
	GetAgent(ctx context.Context, req *GetAgentRequest, opts ...http.CallOption) (rsp *AgentReply, err error)
	// ListAgents Agent 列表（分页）
	ListAgents(ctx context.Context, req *ListAgentsRequest, opts ...http.CallOption) (rsp *ListAgentsReply, err error)
	// ListSkills 列出该 Agent 下所有技能（扫描 workspace/skills 子目录，含 SKILL.md 视为有效）
	ListSkills(ctx context.Context, req *ListSkillsRequest, opts ...http.CallOption) (rsp *ListSkillsReply, err error)
	// UnbindTools 解绑工具
	UnbindTools(ctx context.Context, req *UnbindToolsRequest, opts ...http.CallOption) (rsp *UnbindToolsReply, err error)
	// UpdateAgent 更新 Agent
	UpdateAgent(ctx context.Context, req *UpdateAgentRequest, opts ...http.CallOption) (rsp *AgentReply, err error)
	// UploadSkillPackage 上传技能包（校验通过后解压到 workspace/skills）
	UploadSkillPackage(ctx context.Context, req *UploadSkillPackageRequest, opts ...http.CallOption) (rsp *UploadSkillPackageReply, err error)
	// ValidateSkillPackage 校验技能包（仅校验不解压）
	ValidateSkillPackage(ctx context.Context, req *ValidateSkillPackageRequest, opts ...http.CallOption) (rsp *ValidateSkillPackageReply, err error)
}

type AgentHTTPClientImpl struct {
	cc *http.Client
}

func NewAgentHTTPClient(client *http.Client) AgentHTTPClient {
	return &AgentHTTPClientImpl{client}
}

// BindTools 绑定工具
func (c *AgentHTTPClientImpl) BindTools(ctx context.Context, in *BindToolsRequest, opts ...http.CallOption) (*BindToolsReply, error) {
	var out BindToolsReply
	pattern := "/api/v1/agents/{id}/tools"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAgentBindTools))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Chat 与 Agent 对话
func (c *AgentHTTPClientImpl) Chat(ctx context.Context, in *ChatRequest, opts ...http.CallOption) (*ChatReply, error) {
	var out ChatReply
	pattern := "/api/v1/agents/{id}/chat"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAgentChat))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateAgent 创建 Agent
func (c *AgentHTTPClientImpl) CreateAgent(ctx context.Context, in *CreateAgentRequest, opts ...http.CallOption) (*AgentReply, error) {
	var out AgentReply
	pattern := "/api/v1/agents"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAgentCreateAgent))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteAgent 删除 Agent
func (c *AgentHTTPClientImpl) DeleteAgent(ctx context.Context, in *DeleteAgentRequest, opts ...http.CallOption) (*DeleteAgentReply, error) {
	var out DeleteAgentReply
	pattern := "/api/v1/agents/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAgentDeleteAgent))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteSkill 删除指定技能，移除 workspace/skills/{skill_name}/ 目录及其下所有文件
func (c *AgentHTTPClientImpl) DeleteSkill(ctx context.Context, in *DeleteSkillRequest, opts ...http.CallOption) (*DeleteSkillReply, error) {
	var out DeleteSkillReply
	pattern := "/api/v1/agents/{id}/skills/{skill_name}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAgentDeleteSkill))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ExecuteSkill 执行技能脚本（调试用）
func (c *AgentHTTPClientImpl) ExecuteSkill(ctx context.Context, in *ExecuteSkillRequest, opts ...http.CallOption) (*ExecuteSkillReply, error) {
	var out ExecuteSkillReply
	pattern := "/api/v1/agents/{id}/skills/execute"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAgentExecuteSkill))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetAgent 获取单个 Agent
func (c *AgentHTTPClientImpl) GetAgent(ctx context.Context, in *GetAgentRequest, opts ...http.CallOption) (*AgentReply, error) {
	var out AgentReply
	pattern := "/api/v1/agents/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAgentGetAgent))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAgents Agent 列表（分页）
func (c *AgentHTTPClientImpl) ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...http.CallOption) (*ListAgentsReply, error) {
	var out ListAgentsReply
	pattern := "/api/v1/agents"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAgentListAgents))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListSkills 列出该 Agent 下所有技能（扫描 workspace/skills 子目录，含 SKILL.md 视为有效）
func (c *AgentHTTPClientImpl) ListSkills(ctx context.Context, in *ListSkillsRequest, opts ...http.CallOption) (*ListSkillsReply, error) {
	var out ListSkillsReply
	pattern := "/api/v1/agents/{id}/skills"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAgentListSkills))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UnbindTools 解绑工具
func (c *AgentHTTPClientImpl) UnbindTools(ctx context.Context, in *UnbindToolsRequest, opts ...http.CallOption) (*UnbindToolsReply, error) {
	var out UnbindToolsReply
	pattern := "/api/v1/agents/{id}/tools"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAgentUnbindTools))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateAgent 更新 Agent
func (c *AgentHTTPClientImpl) UpdateAgent(ctx context.Context, in *UpdateAgentRequest, opts ...http.CallOption) (*AgentReply, error) {
	var out AgentReply
	pattern := "/api/v1/agents/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAgentUpdateAgent))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UploadSkillPackage 上传技能包（校验通过后解压到 workspace/skills）
func (c *AgentHTTPClientImpl) UploadSkillPackage(ctx context.Context, in *UploadSkillPackageRequest, opts ...http.CallOption) (*UploadSkillPackageReply, error) {
	var out UploadSkillPackageReply
	pattern := "/api/v1/agents/{id}/skills/upload"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAgentUploadSkillPackage))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ValidateSkillPackage 校验技能包（仅校验不解压）
func (c *AgentHTTPClientImpl) ValidateSkillPackage(ctx context.Context, in *ValidateSkillPackageRequest, opts ...http.CallOption) (*ValidateSkillPackageReply, error) {
	var out ValidateSkillPackageReply
	pattern := "/api/v1/agents/{id}/skills/validate"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAgentValidateSkillPackage))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
