// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.34.0
// source: agent/v1/agent.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Agent_CreateAgent_FullMethodName          = "/agent.v1.Agent/CreateAgent"
	Agent_GetAgent_FullMethodName             = "/agent.v1.Agent/GetAgent"
	Agent_ListAgents_FullMethodName           = "/agent.v1.Agent/ListAgents"
	Agent_UpdateAgent_FullMethodName          = "/agent.v1.Agent/UpdateAgent"
	Agent_DeleteAgent_FullMethodName          = "/agent.v1.Agent/DeleteAgent"
	Agent_BindTools_FullMethodName            = "/agent.v1.Agent/BindTools"
	Agent_UnbindTools_FullMethodName          = "/agent.v1.Agent/UnbindTools"
	Agent_Chat_FullMethodName                 = "/agent.v1.Agent/Chat"
	Agent_ValidateSkillPackage_FullMethodName = "/agent.v1.Agent/ValidateSkillPackage"
	Agent_UploadSkillPackage_FullMethodName   = "/agent.v1.Agent/UploadSkillPackage"
	Agent_ExecuteSkill_FullMethodName         = "/agent.v1.Agent/ExecuteSkill"
	Agent_ListSkills_FullMethodName           = "/agent.v1.Agent/ListSkills"
	Agent_DeleteSkill_FullMethodName          = "/agent.v1.Agent/DeleteSkill"
)

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentClient interface {
	// 创建 Agent
	CreateAgent(ctx context.Context, in *CreateAgentRequest, opts ...grpc.CallOption) (*AgentReply, error)
	// 获取单个 Agent
	GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*AgentReply, error)
	// Agent 列表（分页）
	ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsReply, error)
	// 更新 Agent
	UpdateAgent(ctx context.Context, in *UpdateAgentRequest, opts ...grpc.CallOption) (*AgentReply, error)
	// 删除 Agent
	DeleteAgent(ctx context.Context, in *DeleteAgentRequest, opts ...grpc.CallOption) (*DeleteAgentReply, error)
	// 绑定工具
	BindTools(ctx context.Context, in *BindToolsRequest, opts ...grpc.CallOption) (*BindToolsReply, error)
	// 解绑工具
	UnbindTools(ctx context.Context, in *UnbindToolsRequest, opts ...grpc.CallOption) (*UnbindToolsReply, error)
	// 与 Agent 对话
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatReply, error)
	// 校验技能包（仅校验不解压）
	ValidateSkillPackage(ctx context.Context, in *ValidateSkillPackageRequest, opts ...grpc.CallOption) (*ValidateSkillPackageReply, error)
	// 上传技能包（校验通过后解压到 workspace/skills）
	UploadSkillPackage(ctx context.Context, in *UploadSkillPackageRequest, opts ...grpc.CallOption) (*UploadSkillPackageReply, error)
	// 执行技能脚本（调试用）
	ExecuteSkill(ctx context.Context, in *ExecuteSkillRequest, opts ...grpc.CallOption) (*ExecuteSkillReply, error)
	// 列出该 Agent 下所有技能（扫描 workspace/skills 子目录，含 SKILL.md 视为有效）
	ListSkills(ctx context.Context, in *ListSkillsRequest, opts ...grpc.CallOption) (*ListSkillsReply, error)
	// 删除指定技能，移除 workspace/skills/{skill_name}/ 目录及其下所有文件
	DeleteSkill(ctx context.Context, in *DeleteSkillRequest, opts ...grpc.CallOption) (*DeleteSkillReply, error)
}

type agentClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentClient(cc grpc.ClientConnInterface) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) CreateAgent(ctx context.Context, in *CreateAgentRequest, opts ...grpc.CallOption) (*AgentReply, error) {
	out := new(AgentReply)
	err := c.cc.Invoke(ctx, Agent_CreateAgent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*AgentReply, error) {
	out := new(AgentReply)
	err := c.cc.Invoke(ctx, Agent_GetAgent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsReply, error) {
	out := new(ListAgentsReply)
	err := c.cc.Invoke(ctx, Agent_ListAgents_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) UpdateAgent(ctx context.Context, in *UpdateAgentRequest, opts ...grpc.CallOption) (*AgentReply, error) {
	out := new(AgentReply)
	err := c.cc.Invoke(ctx, Agent_UpdateAgent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) DeleteAgent(ctx context.Context, in *DeleteAgentRequest, opts ...grpc.CallOption) (*DeleteAgentReply, error) {
	out := new(DeleteAgentReply)
	err := c.cc.Invoke(ctx, Agent_DeleteAgent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) BindTools(ctx context.Context, in *BindToolsRequest, opts ...grpc.CallOption) (*BindToolsReply, error) {
	out := new(BindToolsReply)
	err := c.cc.Invoke(ctx, Agent_BindTools_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) UnbindTools(ctx context.Context, in *UnbindToolsRequest, opts ...grpc.CallOption) (*UnbindToolsReply, error) {
	out := new(UnbindToolsReply)
	err := c.cc.Invoke(ctx, Agent_UnbindTools_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatReply, error) {
	out := new(ChatReply)
	err := c.cc.Invoke(ctx, Agent_Chat_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ValidateSkillPackage(ctx context.Context, in *ValidateSkillPackageRequest, opts ...grpc.CallOption) (*ValidateSkillPackageReply, error) {
	out := new(ValidateSkillPackageReply)
	err := c.cc.Invoke(ctx, Agent_ValidateSkillPackage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) UploadSkillPackage(ctx context.Context, in *UploadSkillPackageRequest, opts ...grpc.CallOption) (*UploadSkillPackageReply, error) {
	out := new(UploadSkillPackageReply)
	err := c.cc.Invoke(ctx, Agent_UploadSkillPackage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ExecuteSkill(ctx context.Context, in *ExecuteSkillRequest, opts ...grpc.CallOption) (*ExecuteSkillReply, error) {
	out := new(ExecuteSkillReply)
	err := c.cc.Invoke(ctx, Agent_ExecuteSkill_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ListSkills(ctx context.Context, in *ListSkillsRequest, opts ...grpc.CallOption) (*ListSkillsReply, error) {
	out := new(ListSkillsReply)
	err := c.cc.Invoke(ctx, Agent_ListSkills_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) DeleteSkill(ctx context.Context, in *DeleteSkillRequest, opts ...grpc.CallOption) (*DeleteSkillReply, error) {
	out := new(DeleteSkillReply)
	err := c.cc.Invoke(ctx, Agent_DeleteSkill_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServer is the server API for Agent service.
// All implementations must embed UnimplementedAgentServer
// for forward compatibility
type AgentServer interface {
	// 创建 Agent
	CreateAgent(context.Context, *CreateAgentRequest) (*AgentReply, error)
	// 获取单个 Agent
	GetAgent(context.Context, *GetAgentRequest) (*AgentReply, error)
	// Agent 列表（分页）
	ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsReply, error)
	// 更新 Agent
	UpdateAgent(context.Context, *UpdateAgentRequest) (*AgentReply, error)
	// 删除 Agent
	DeleteAgent(context.Context, *DeleteAgentRequest) (*DeleteAgentReply, error)
	// 绑定工具
	BindTools(context.Context, *BindToolsRequest) (*BindToolsReply, error)
	// 解绑工具
	UnbindTools(context.Context, *UnbindToolsRequest) (*UnbindToolsReply, error)
	// 与 Agent 对话
	Chat(context.Context, *ChatRequest) (*ChatReply, error)
	// 校验技能包（仅校验不解压）
	ValidateSkillPackage(context.Context, *ValidateSkillPackageRequest) (*ValidateSkillPackageReply, error)
	// 上传技能包（校验通过后解压到 workspace/skills）
	UploadSkillPackage(context.Context, *UploadSkillPackageRequest) (*UploadSkillPackageReply, error)
	// 执行技能脚本（调试用）
	ExecuteSkill(context.Context, *ExecuteSkillRequest) (*ExecuteSkillReply, error)
	// 列出该 Agent 下所有技能（扫描 workspace/skills 子目录，含 SKILL.md 视为有效）
	ListSkills(context.Context, *ListSkillsRequest) (*ListSkillsReply, error)
	// 删除指定技能，移除 workspace/skills/{skill_name}/ 目录及其下所有文件
	DeleteSkill(context.Context, *DeleteSkillRequest) (*DeleteSkillReply, error)
	mustEmbedUnimplementedAgentServer()
}

// UnimplementedAgentServer must be embedded to have forward compatible implementations.
type UnimplementedAgentServer struct {
}

func (UnimplementedAgentServer) CreateAgent(context.Context, *CreateAgentRequest) (*AgentReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAgent not implemented")
}
func (UnimplementedAgentServer) GetAgent(context.Context, *GetAgentRequest) (*AgentReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgent not implemented")
}
func (UnimplementedAgentServer) ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAgents not implemented")
}
func (UnimplementedAgentServer) UpdateAgent(context.Context, *UpdateAgentRequest) (*AgentReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAgent not implemented")
}
func (UnimplementedAgentServer) DeleteAgent(context.Context, *DeleteAgentRequest) (*DeleteAgentReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAgent not implemented")
}
func (UnimplementedAgentServer) BindTools(context.Context, *BindToolsRequest) (*BindToolsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BindTools not implemented")
}
func (UnimplementedAgentServer) UnbindTools(context.Context, *UnbindToolsRequest) (*UnbindToolsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnbindTools not implemented")
}
func (UnimplementedAgentServer) Chat(context.Context, *ChatRequest) (*ChatReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedAgentServer) ValidateSkillPackage(context.Context, *ValidateSkillPackageRequest) (*ValidateSkillPackageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateSkillPackage not implemented")
}
func (UnimplementedAgentServer) UploadSkillPackage(context.Context, *UploadSkillPackageRequest) (*UploadSkillPackageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadSkillPackage not implemented")
}
func (UnimplementedAgentServer) ExecuteSkill(context.Context, *ExecuteSkillRequest) (*ExecuteSkillReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteSkill not implemented")
}
func (UnimplementedAgentServer) ListSkills(context.Context, *ListSkillsRequest) (*ListSkillsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSkills not implemented")
}
func (UnimplementedAgentServer) DeleteSkill(context.Context, *DeleteSkillRequest) (*DeleteSkillReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSkill not implemented")
}
func (UnimplementedAgentServer) mustEmbedUnimplementedAgentServer() {}

// UnsafeAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServer will
// result in compilation errors.
type UnsafeAgentServer interface {
	mustEmbedUnimplementedAgentServer()
}

func RegisterAgentServer(s grpc.ServiceRegistrar, srv AgentServer) {
	s.RegisterService(&Agent_ServiceDesc, srv)
}

func _Agent_CreateAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).CreateAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_CreateAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).CreateAgent(ctx, req.(*CreateAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_GetAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).GetAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_GetAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).GetAgent(ctx, req.(*GetAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ListAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ListAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ListAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ListAgents(ctx, req.(*ListAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_UpdateAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).UpdateAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_UpdateAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).UpdateAgent(ctx, req.(*UpdateAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_DeleteAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).DeleteAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_DeleteAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).DeleteAgent(ctx, req.(*DeleteAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_BindTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindToolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).BindTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_BindTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).BindTools(ctx, req.(*BindToolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_UnbindTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnbindToolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).UnbindTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_UnbindTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).UnbindTools(ctx, req.(*UnbindToolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_Chat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Chat(ctx, req.(*ChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ValidateSkillPackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateSkillPackageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ValidateSkillPackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ValidateSkillPackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ValidateSkillPackage(ctx, req.(*ValidateSkillPackageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_UploadSkillPackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadSkillPackageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).UploadSkillPackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_UploadSkillPackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).UploadSkillPackage(ctx, req.(*UploadSkillPackageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ExecuteSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ExecuteSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ExecuteSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ExecuteSkill(ctx, req.(*ExecuteSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ListSkills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSkillsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ListSkills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ListSkills_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ListSkills(ctx, req.(*ListSkillsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_DeleteSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).DeleteSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_DeleteSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).DeleteSkill(ctx, req.(*DeleteSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Agent_ServiceDesc is the grpc.ServiceDesc for Agent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Agent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.v1.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAgent",
			Handler:    _Agent_CreateAgent_Handler,
		},
		{
			MethodName: "GetAgent",
			Handler:    _Agent_GetAgent_Handler,
		},
		{
			MethodName: "ListAgents",
			Handler:    _Agent_ListAgents_Handler,
		},
		{
			MethodName: "UpdateAgent",
			Handler:    _Agent_UpdateAgent_Handler,
		},
		{
			MethodName: "DeleteAgent",
			Handler:    _Agent_DeleteAgent_Handler,
		},
		{
			MethodName: "BindTools",
			Handler:    _Agent_BindTools_Handler,
		},
		{
			MethodName: "UnbindTools",
			Handler:    _Agent_UnbindTools_Handler,
		},
		{
			MethodName: "Chat",
			Handler:    _Agent_Chat_Handler,
		},
		{
			MethodName: "ValidateSkillPackage",
			Handler:    _Agent_ValidateSkillPackage_Handler,
		},
		{
			MethodName: "UploadSkillPackage",
			Handler:    _Agent_UploadSkillPackage_Handler,
		},
		{
			MethodName: "ExecuteSkill",
			Handler:    _Agent_ExecuteSkill_Handler,
		},
		{
			MethodName: "ListSkills",
			Handler:    _Agent_ListSkills_Handler,
		},
		{
			MethodName: "DeleteSkill",
			Handler:    _Agent_DeleteSkill_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent/v1/agent.proto",
}
