// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"backend/internal/biz"
	"backend/internal/conf"
	"backend/internal/cron"
	"backend/internal/data"
	"backend/internal/runtime"
	"backend/internal/server"
	"backend/internal/service"
	"backend/internal/terminal"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"time"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, auth *conf.Auth, growth *conf.Growth, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, auth, logger)
	if err != nil {
		return nil, nil, err
	}
	toolRepo := data.NewToolRepo(dataData, logger)
	resourceRepo := data.NewResourceRepo(dataData, logger)
	accessChecker := biz.ProvideAccessChecker(resourceRepo)
	proxyRepo := data.NewProxyRepo(dataData, logger)
	toolUsecase := biz.NewToolUsecase(toolRepo, resourceRepo, accessChecker, proxyRepo, logger)
	toolService := service.NewToolService(toolUsecase)
	agentRepo := data.NewAgentRepo(dataData, confData, logger)
	string2 := data.ProvideDataRoot(confData)
	agentUsecase := biz.NewAgentUsecase(agentRepo, resourceRepo, accessChecker, proxyRepo, string2, logger)
	mcpServerRepo := data.NewMcpServerRepo(dataData, logger)
	mcpServerUsecase := biz.NewMcpServerUsecase(mcpServerRepo, resourceRepo, accessChecker, logger)
	identityRepo := data.NewIdentityRepo(dataData, logger)
	skillResourceUsecase := biz.NewSkillResourceUsecase(identityRepo, resourceRepo, string2)
	channelRepo := data.NewChannelRepo(dataData, logger)
	channelUsecase := biz.NewChannelUsecase(channelRepo, agentRepo, logger)
	v := data.ProvideCodeRoots(confData)
	agentService := service.NewAgentService(agentUsecase, toolUsecase, mcpServerUsecase, skillResourceUsecase, channelUsecase, proxyRepo, v, logger)
	repoRegistryRepo := data.NewRepoRegistryRepo(dataData, logger)
	repoRegistryUsecase := biz.NewRepoRegistryUsecase(repoRegistryRepo, agentRepo, v, logger)
	agentService.SetRCARootResolver(repoRegistryUsecase)
	chatSessionRepo := data.NewChatSessionRepo(dataData, logger)
	chatMessageRepo := data.NewChatMessageRepo(dataData, logger)
	attachmentRepo := data.NewChatAttachmentRepo(dataData, logger)
	chatUsecase := biz.NewChatUsecase(chatSessionRepo, chatMessageRepo, agentRepo, resourceRepo, accessChecker, attachmentRepo)
	sessionUnitsBackend := data.NewSessionUnitsBackendFromData(dataData)
	store := data.NewTurnTraceStoreFromData(dataData)
	evolutionProposalRepo := data.NewEvolutionProposalRepo(dataData, logger)
	chatService := service.ProvideChatServiceWithTurnTrace(chatUsecase, agentUsecase, toolUsecase, mcpServerUsecase, skillResourceUsecase, channelUsecase, sessionUnitsBackend, store, v, dataData, proxyRepo, evolutionProposalRepo, logger)
	chatService.SetRCARootResolver(repoRegistryUsecase)
	grpcServer := server.NewGRPCServer(confServer, toolService, agentService, chatService, logger)
	channelRuntimeRepo := data.NewChannelRuntimeRepo(dataData, logger)
	channelService := service.NewChannelService(channelUsecase, channelRuntimeRepo, agentService, logger)
	cronTaskRepo := data.NewCronTaskRepo(dataData, logger)
	cronRunRepo := data.NewCronRunRepo(dataData, logger)
	cronUsecase := biz.NewCronUsecase(cronTaskRepo, cronRunRepo, logger)
	executor := cron.NewExecutor(agentService, chatUsecase, cronUsecase, channelUsecase, auth, logger)
	cronService := cron.NewCronService(cronUsecase, executor)
	inviteRepo := data.NewInviteRepo(dataData, logger)
	aclapiUsecase := biz.ProvideACLAPIUsecase(identityRepo, resourceRepo, inviteRepo, accessChecker, auth)
	authEphemeralRepo := data.NewAuthEphemeralRepo(dataData, logger)
	authUsecase := biz.ProvideAuthUsecase(identityRepo, inviteRepo, authEphemeralRepo, auth)
	mcpServerService := service.NewMcpServerService(mcpServerUsecase, logger)
	proxyUsecase := biz.NewProxyUsecase(proxyRepo, resourceRepo, accessChecker, logger)
	proxyService := service.NewProxyService(proxyUsecase, logger)
	channelPeerSessionRepo := data.NewChannelPeerSessionRepo(dataData, logger)
	channelPeerUsecase := biz.NewChannelPeerUsecase(channelPeerSessionRepo, chatSessionRepo, channelRepo)
	agentRouteUsecase := runtime.ProvideAgentRouteUsecase(channelRepo, channelPeerSessionRepo, agentUsecase, growth, logger)
	runtimeService := runtime.NewService(chatUsecase, channelPeerUsecase, channelUsecase, agentUsecase, chatSessionRepo, channelRuntimeRepo, chatService, chatService, agentRouteUsecase)
	db := data.ProvideDB(dataData)
	terminalIdleTTL := provideTerminalIdleTTL()
	manager := terminal.NewManager(db, terminalIdleTTL)
	evolutionUsecase := biz.NewEvolutionUsecase(evolutionProposalRepo)
	httpServer := server.NewHTTPServer(confServer, toolService, agentService, chatService, channelService, cronService, channelUsecase, identityRepo, aclapiUsecase, authUsecase, mcpServerService, proxyService, runtimeService, dataData, agentUsecase, v, logger, manager, agentRepo, toolUsecase, evolutionUsecase, repoRegistryUsecase)
	duration := cron.ProvideSchedulerInterval()
	scheduler := cron.NewScheduler(cronUsecase, executor, duration, logger)
	scheduler.SetEvolutionUsecase(evolutionUsecase)
	scheduler.SetRepoRegistry(repoRegistryUsecase, cron.DefaultRepoScanInterval)
	cronServer := cron.NewServer(scheduler)
	app := newApp(logger, grpcServer, httpServer, cronServer)
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

// provideTerminalIdleTTL returns the terminal session idle TTL for wire DI.
func provideTerminalIdleTTL() terminal.TerminalIdleTTL {
	return terminal.TerminalIdleTTL(30 * time.Minute)
}
