// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"backend/internal/biz"
	"backend/internal/conf"
	"backend/internal/cron"
	"backend/internal/data"
	"backend/internal/runtime"
	"backend/internal/server"
	"backend/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, auth *conf.Auth, mainLlmReviewEnabledInput llmReviewEnabledInput, mainGrowthReviewPatchFileInput growthReviewPatchFileInput, mainCuratorPatchFileInput curatorPatchFileInput, mainWorkerEnabledInput workerEnabledInput, growth *conf.Growth, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, auth, logger)
	if err != nil {
		return nil, nil, err
	}
	toolRepo := data.NewToolRepo(dataData, logger)
	resourceRepo := data.NewResourceRepo(dataData, logger)
	accessChecker := biz.ProvideAccessChecker(resourceRepo)
	toolUsecase := biz.NewToolUsecase(toolRepo, resourceRepo, accessChecker, logger)
	toolService := service.NewToolService(toolUsecase)
	agentRepo := data.NewAgentRepo(dataData, confData, logger)
	string2 := data.ProvideDataRoot(confData)
	agentUsecase := biz.NewAgentUsecase(agentRepo, resourceRepo, accessChecker, string2, logger)
	mcpServerRepo := data.NewMcpServerRepo(dataData, logger)
	mcpServerUsecase := biz.NewMcpServerUsecase(mcpServerRepo, resourceRepo, accessChecker, logger)
	identityRepo := data.NewIdentityRepo(dataData, logger)
	skillResourceUsecase := biz.NewSkillResourceUsecase(identityRepo, resourceRepo, string2)
	channelRepo := data.NewChannelRepo(dataData, logger)
	channelUsecase := biz.NewChannelUsecase(channelRepo, agentRepo, logger)
	agentService := service.NewAgentService(agentUsecase, toolUsecase, mcpServerUsecase, skillResourceUsecase, channelUsecase, logger)
	chatSessionRepo := data.NewChatSessionRepo(dataData, logger)
	chatMessageRepo := data.NewChatMessageRepo(dataData, logger)
	chatUsecase := biz.NewChatUsecase(chatSessionRepo, chatMessageRepo, agentRepo, resourceRepo, accessChecker)
	growthRepo := data.NewGrowthRepo(dataData, logger)
	growthUsecase := biz.ProvideGrowthUsecase(growthRepo, growth)
	sessionUnitsBackend := data.NewSessionUnitsBackendFromData(dataData)
	store := data.NewTurnTraceStoreFromData(dataData)
	chatService := service.ProvideChatServiceWithTurnTrace(chatUsecase, agentUsecase, toolUsecase, mcpServerUsecase, skillResourceUsecase, growthUsecase, channelUsecase, sessionUnitsBackend, store, dataData, logger)
	grpcServer := server.NewGRPCServer(confServer, toolService, agentService, chatService, logger)
	channelRuntimeRepo := data.NewChannelRuntimeRepo(dataData, logger)
	channelService := service.NewChannelService(channelUsecase, channelRuntimeRepo, agentService, logger)
	cronTaskRepo := data.NewCronTaskRepo(dataData, logger)
	cronRunRepo := data.NewCronRunRepo(dataData, logger)
	cronUsecase := biz.NewCronUsecase(cronTaskRepo, cronRunRepo, logger)
	executor := cron.NewExecutor(agentService, chatUsecase, cronUsecase, channelUsecase, auth, logger)
	cronService := cron.NewCronService(cronUsecase, executor)
	inviteRepo := data.NewInviteRepo(dataData, logger)
	aclapiUsecase := biz.ProvideACLAPIUsecase(identityRepo, resourceRepo, inviteRepo, accessChecker, auth)
	authUsecase := biz.ProvideAuthUsecase(identityRepo, inviteRepo, auth)
	mcpServerService := service.NewMcpServerService(mcpServerUsecase, logger)
	channelPeerSessionRepo := data.NewChannelPeerSessionRepo(dataData, logger)
	channelPeerUsecase := biz.NewChannelPeerUsecase(channelPeerSessionRepo, chatSessionRepo, channelRepo)
	runtimeService := runtime.NewService(chatUsecase, channelPeerUsecase, channelUsecase, agentUsecase, chatSessionRepo, channelRuntimeRepo, chatService, chatService)
	httpServer := server.NewHTTPServer(confServer, toolService, agentService, chatService, channelService, cronService, channelUsecase, identityRepo, aclapiUsecase, authUsecase, mcpServerService, runtimeService, dataData, logger)
	duration := cron.ProvideSchedulerInterval()
	scheduler := cron.NewScheduler(cronUsecase, executor, duration, logger)
	cronServer := cron.NewServer(scheduler)
	cronRefRewriteUsecase := biz.ProvideCronRefRewriteUsecase(cronTaskRepo, agentRepo)
	growthWorker := provideGrowthWorker(logger, chatUsecase, agentUsecase, growthUsecase, cronRefRewriteUsecase, auth, mainLlmReviewEnabledInput, mainGrowthReviewPatchFileInput, growth, mainWorkerEnabledInput, store)
	curatorRepo := data.NewCuratorRepo(dataData, logger)
	curatorUsecase := biz.ProvideCuratorUsecase(curatorRepo, agentRepo, growthUsecase)
	curatorWorker := provideCuratorWorker(logger, curatorUsecase, cronRefRewriteUsecase, growth, mainLlmReviewEnabledInput, mainCuratorPatchFileInput)
	app := newApp(logger, grpcServer, httpServer, cronServer, chatService, growthWorker, curatorWorker, mainWorkerEnabledInput)
	return app, func() {
		cleanup()
	}, nil
}
