package handbook

import (
	"context"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func writeTree(t *testing.T, root string, files map[string]string) {
	t.Helper()
	for rel, content := range files {
		p := filepath.Join(root, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
}

const orderStoreGo = `// Package order persists orders.
package order

import "database/sql"

type Store struct{ db *sql.DB }

type Order struct{ ID int64 }

func (Order) TableName() string { return "orders" }

func (s *Store) Get(id int64) error {
	_, err := s.db.Query("SELECT id FROM orders WHERE id = ?", id)
	return err
}

func (s *Store) MarkPaid(id int64) error {
	_, err := s.db.Exec("UPDATE orders SET status = 'paid' WHERE id = ?", id)
	return err
}
`

func sampleRepo(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	writeTree(t, root, map[string]string{
		"go.mod":                       "module example.com/svc\n\ngo 1.22\n\nrequire (\n\tgithub.com/a/b v1.0.0\n\tgithub.com/c/d v1.0.0 // indirect\n)\n",
		"go.sum":                       "ignored\n",
		"cmd/server/main.go":           "package main\n\nfunc main() {}\n",
		"internal/order/store.go":      orderStoreGo,
		"internal/order/store_test.go": "package order\n\nfunc TestX() {}\n",
		"vendor/x/x.go":                "package x\n",
		".github/ci.yml":               "on: push\n",
		"api/pb/order.pb.go":           "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage pb\n",
		"assets/logo.png":              "\x89PNG\x00\x00binary",
		"big.txt":                      strings.Repeat("x", MaxFileBytes+1),
		"README.md":                    "# svc\n",
	})
	return root
}

func TestCollectFacts_FiltersAndHashes(t *testing.T) {
	f, err := CollectFacts(context.Background(), sampleRepo(t))
	if err != nil {
		t.Fatal(err)
	}
	var paths []string
	for _, file := range f.Files {
		paths = append(paths, file.Path)
		if len(file.Hash) != 64 {
			t.Fatalf("hash of %s = %q", file.Path, file.Hash)
		}
	}
	want := "README.md,cmd/server/main.go,go.mod,internal/order/store.go,internal/order/store_test.go"
	if got := strings.Join(paths, ","); got != want {
		t.Fatalf("files = %s\nwant    %s", got, want)
	}
	c := f.Coverage
	if c.SkippedBinary != 1 || c.SkippedGenerated != 1 || c.SkippedLarge != 1 || c.Truncated || c.Graph != "none" {
		t.Fatalf("coverage = %#v", c)
	}
	for _, file := range f.Files {
		if file.Path == "internal/order/store_test.go" && !file.Test {
			t.Fatal("store_test.go should be marked as test")
		}
		if file.Path == "internal/order/store.go" && (file.Lang != "go" || file.Lines != 20) {
			t.Fatalf("store.go = %#v", file)
		}
	}
}

func TestCollectFacts_GoPackagesAndModule(t *testing.T) {
	f, err := CollectFacts(context.Background(), sampleRepo(t))
	if err != nil {
		t.Fatal(err)
	}
	if f.Module == nil || f.Module.Path != "example.com/svc" || strings.Join(f.Module.Requires, ",") != "github.com/a/b" {
		t.Fatalf("module = %#v", f.Module)
	}
	if len(f.Packages) != 2 {
		t.Fatalf("packages = %#v", f.Packages)
	}
	main, order := f.Packages[0], f.Packages[1]
	if main.Dir != "cmd/server" || !main.Main || order.Dir != "internal/order" || order.Name != "order" || order.Doc != "Package order persists orders." || order.Files != 1 {
		t.Fatalf("packages = %#v", f.Packages)
	}
	if len(f.Symbols["internal/order/store.go"]) == 0 || len(f.Symbols["internal/order/store_test.go"]) != 0 {
		t.Fatalf("symbols = %#v", f.Symbols)
	}
}

func TestCollectFacts_TruncatesAtMaxFiles(t *testing.T) {
	root := t.TempDir()
	files := map[string]string{}
	for i := 0; i < 5; i++ {
		files[filepath.ToSlash(filepath.Join("d", string(rune('a'+i))+".txt"))] = "x\n"
	}
	writeTree(t, root, files)
	f, err := collectFacts(context.Background(), root, 3)
	if err != nil {
		t.Fatal(err)
	}
	if len(f.Files) != 3 || !f.Coverage.Truncated {
		t.Fatalf("files=%d truncated=%v", len(f.Files), f.Coverage.Truncated)
	}
}

type staleEntry struct {
	fs.DirEntry
	size int64
}

func (e staleEntry) Info() (fs.FileInfo, error) {
	info, err := e.DirEntry.Info()
	return staleInfo{info, e.size}, err
}

type staleInfo struct {
	fs.FileInfo
	size int64
}

func (i staleInfo) Size() int64 { return i.size }

func TestAddFile_GrewAfterStat(t *testing.T) {
	root := t.TempDir()
	writeTree(t, root, map[string]string{"big.txt": strings.Repeat("x", MaxFileBytes+10)})
	ents, err := os.ReadDir(root)
	if err != nil || len(ents) != 1 {
		t.Fatalf("ents=%v err=%v", ents, err)
	}
	f := &Facts{Symbols: map[string][]Symbol{}}
	if err := f.addFile(filepath.Join(root, "big.txt"), "big.txt", staleEntry{ents[0], 10}, map[string]*GoPackage{}); err != nil {
		t.Fatal(err)
	}
	if len(f.Files) != 0 || f.Coverage.SkippedLarge != 1 {
		t.Fatalf("files=%v coverage=%#v", f.Files, f.Coverage)
	}
}

func TestCollectFacts_MissingRoot(t *testing.T) {
	if _, err := CollectFacts(context.Background(), filepath.Join(t.TempDir(), "nope")); err == nil {
		t.Fatal("missing root must fail")
	}
}
